### ISSUE TITLE
contract interaction: validate args inputs

### ISSUE THREAD

**Issue by tom2drum** [blockscout/frontend#1035]
validation rules for each type of args:

- boolean - `bool`
  -  has to be literal string either `true` or `false` with all possible variations of letter-case (`tRuE` is correct), or either `1` or `0`
- string - `string`
  - is not validated
- integer - `int`, `int8`, etc
  - can contain only digits `[0-9]` and signs `-` or `+`
  - min and max values are validated according to integer size (`-128…127` for `int8`)
  - ~can contain thousands separators like `_` or `,`~ decided to use masked inputs
- unsigned integer - `uint`, `uint8`, etc
  - can contain only digits `[0-9]` and sign `+`
  - min and max values are validated according to integer size (`-128…127` for `int8`)
  - ~can contain thousands separators like `_` or `,`~ decided to use masked inputs
- address - `address`
  - string that matches regexp `/^0x[a-fA-F\d]{40}$/`
  - length is equal 42
  - checksum is valid
- fixed-size byte array - `bytes1`, `bytes2`, etc
  - input format
    - hex (`0x112233` for `bytes3`); empty value is `0x`
    - ASCII string (`foo`) with length less or equal array size; empty value is `""`
- dynamically-sized byte array - `bytes`
  - similar to `bytes1[]`, `bytes2`, etc
- array - `T[k]` where `T` can be any of the above types and `k` is array size (optional)
  - possible input format example - `[4, 3, 2, 1]` - in square brackets type elements separated by comma and white space (optional)
  - each element should follow validation rules for the type
  - ?? how highlight error for a specific element of the array; maybe we need separate input for each element
  - arrays can be nested in each other - `[ [ 1, 2 ], [ [ 3, 4 ] ], [ [ [ 5 ], 6 ], 7 ]`
- functions - `function`
  - rare case; will not be supported
- tuples - `tuple`
  - similar to array with elements of different type - `[ 1, true, 0x112233]`
- structs - `struct`
  - ?? difficult to manage
  ```
    struct(
       txHash: 0x4977044e3c1c2f2c6fd987639a93ee8e7ca9ae16e6b204ceec237a826eb0520c
       blockNumber: 1000
       logs: [ 1, 3, 7 ]
    )
  ```

**Comment by tgladilina** [comment]
**Ready to discuss**

![Image](https://github.com/blockscout/frontend/assets/103045386/d47c1d75-2752-4d5c-a07f-887482414ac4)

**Comment by NikitaSavik** [comment]
@tgladilina to be reworked:
show fields in a column (instead of the flex row)

**Comment by tgladilina** [comment]
**Updated**

![Image](https://github.com/blockscout/frontend/assets/103045386/59c68ddc-ae40-429f-997b-b637b0715246)


![Image](https://github.com/blockscout/frontend/assets/103045386/2981819c-ba3e-4ef2-a2d9-a9af8ad67532)
