### ISSUE TITLE
unified page title snippets

### ISSUE THREAD

**Issue by tom2drum** [blockscout/frontend#1110]
https://www.figma.com/file/4In0X8UADoZaTfZ34HaZ3K/Blockscout_2.0?type=design&node-id=7%3A4&mode=dev

**Comment by tgladilina** [comment]
https://www.notion.so/blockscout/Design-For-Page-titels-format-for-all-pages-092991ac17404837801b10bafa2d7d09?pvs=4

![Image](https://github.com/blockscout/frontend/assets/103045386/34a038fb-a75c-42cf-8c53-61c9c1a81934)
![Image](https://github.com/blockscout/frontend/assets/103045386/e3442542-ebb1-4f12-b67b-d06d50570652)
![Image](https://github.com/blockscout/frontend/assets/103045386/a1d2bafd-8db0-4069-96b1-926ef490a566)
