### ISSUE TITLE
Allow adding capability to display alert/announcement in the new UI

### ISSUE THREAD

**Issue by vbaranov** [blockscout/frontend#1123]
### Description

In the old UI it is managed via `SHOW_MAINTENANCE_ALERT` (true/false) and `MAINTENANCE_ALERT_MESSAGE` is for HTML/text message.

### Link to the page

https://eth.blockscout.com

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### App version

v.1.9.0

### Operating system

None

**Comment by isstuev** [comment]
use gray alert to display that info

![Image](https://github.com/blockscout/frontend/assets/108066576/daaf8c0b-8bd9-4891-a110-64eb78dc8a0b)

**Comment by tom2drum** [comment]
@vbaranov can you provide an example value for `MAINTENANCE_ALERT_MESSAGE` for test purposes?

**Comment by vbaranov** [comment]
> @vbaranov can you provide an example value for `MAINTENANCE_ALERT_MESSAGE` for test purposes?

e.g.
```
The Sokol Testnet is currently lacking validators. Please consider using <a href="https://eth-goerli.blockscout.com/">Goerli</a> or <a href="https://mumbai.polygonscan.com/">Mumbai</a> for testing purposes.
```

**Comment by tom2drum** [comment]
@vbaranov is it OK if we use just one variable `NEXT_PUBLIC_MAINTENANCE_ALERT_MESSAGE`? If it is present, we will display the message.

**Comment by vbaranov** [comment]
> @vbaranov is it OK if we use just one variable `NEXT_PUBLIC_MAINTENANCE_ALERT_MESSAGE`? If it is present, we will display the message.

Yeah, I think 1 env var would be pretty much it.

**Comment by tom2drum** [comment]
And what if we have two alerts to display for indexing blocks and for maintenance, should we show both, one below the other?

**Comment by vbaranov** [comment]
> And what if we have two alerts to display for indexing blocks and for maintenance, should we show both, one below the other?

Yep, one below the other sounds good.
