### ISSUE TITLE
Add tags to reorg blocks in search and quicksearch

### ISSUE THREAD

**Issue by ulyanas** [blockscout/frontend#1131]
Reorg/Uncle blocks to be identified by tag in the search result

![Image](https://user-images.githubusercontent.com/1701762/265407080-66274f7d-6445-422b-9700-5108614ed1d8.png)

**Comment by NikitaSavik** [comment]
@nikitosing to link backend task

**Comment by isstuev** [comment]
https://eth.blockscout.com/api/v2/search?q=18276809
