### ISSUE TITLE
Block tile: reward splitted in 2 lines

### ISSUE THREAD

**Issue by vbaranov** [blockscout/frontend#1132]
### Description

![Screenshot 2023-09-04 at 18 48 20](https://github.com/blockscout/frontend/assets/4341812/2e382374-dccc-4e86-8ea2-9386e6b4de29)

### Link to the page

https://eth.blockscout.com/

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### App version

v1.10.0

### Operating system

None

**Comment by tom2drum** [comment]
closing as duplicate #1143
