### ISSUE TITLE
Charts&Stats: add tooltips to number charts

### ISSUE THREAD

**Issue by isstuev** [blockscout/frontend#1151]
Need to add tooltips for all number charts

Number charts types:
1) Average block time
Description: Average time taken in seconds for a block to be included in the blockchain

2) Total accounts
Description: Number of EOAs that sent at least 1 transaction

3) Total tokens
Description: Number of all token contracts

4) Completed txns
Description: Number of transactions with success status

5) Total blocks
Description: Number of blocks over all time

6) Total txns
Description: All transactions including pending, dropped, replaced, failed transactions

7) Number of deployed contracts today
Description: Number of deployed contracts today

8) Total contracts
Description: Number of contracts

9) Total verified contracts
Description: Number of verified contracts

10) Number of verified contracts today
Description: Number of contracts verified today

11) Total native coin transfers
Description: Number of transactions with the transfer of the native coin

12) Total addresses
Description: Number of addresses that participated in the blockchain

**Comment by MaximK3** [comment]
Description:
https://www.notion.so/blockscout/Tooltips-Spec-e85eef0911e848d1b6bc30df908078bf
