### ISSUE TITLE
Contract verification: Improve the selection of a compiler version

### ISSUE THREAD

**Issue by ulyanas** [blockscout/frontend#1164]
Blockscout shortens the list of available Solidity versions and the required version can be only found using 'select' as a search field, it is not obvious to the users.

For example, in that case users were not able to find 0.4.24 right away. 

![Image](https://user-images.githubusercontent.com/6618204/266871173-e61d37b4-daf6-4c53-9fe0-c5ef64e667b1.png)

**Comment by tgladilina** [comment]
****version 1 :** Update placeholder/ label to "Select compiler* from list or start typing v.0..."**

![Image](https://github.com/blockscout/frontend/assets/103045386/9ef17454-9985-46e9-8c5c-59be51a6251a)



****v2.** Replace selector field with Search field +  nightly builds Included always**

2-1  new search field with label 
![Image](https://github.com/blockscout/frontend/assets/103045386/5e7e9846-0ff9-4a5c-9b9c-c21647e457ad)

or 

2-2 search field
![Image](https://github.com/blockscout/frontend/assets/103045386/25cb88ba-39b5-4afe-bdd6-16f514e62834)


@tom2drum cc

**Comment by tgladilina** [comment]
one more option: v3 @tom2drum cc

![Image](https://github.com/blockscout/frontend/assets/103045386/1e4f5a85-aa44-4466-b3eb-43ee7da2cedf)

**Comment by tgladilina** [comment]
**final version**  @tom2drum 

<img width="1208" alt="Screenshot 2023-10-02 at 13 14 25" src="https://github.com/blockscout/frontend/assets/103045386/d755d960-5784-469d-a09a-08f509a203fc">

or just add "search" icon before label and text

<img width="797" alt="Screenshot 2023-10-02 at 13 15 17" src="https://github.com/blockscout/frontend/assets/103045386/f442a24e-da54-41b1-a37f-e242750fbb87">
