### ISSUE TITLE
Add bridged tokens

### ISSUE THREAD

**Issue by ulyanas** [blockscout/frontend#1168]
**Description**:

The Bridged tokens feature in Blockscout allows users to view tokens that have been bridged from other EVM chains. 

- Users can view the list of bridged tokens per the origin chain

- Bridged tokens attributes:
Token | Address | Total supply | Holders count | USD value

- Token details page for bridged token should include a link to the original token and tags `Bridged` and origin network tags like `ETH`, `BSC`, etc.  

- Search control should be available for the list

**UI**:
Need to redesign this page in the UI: https://explorer.fuse.io/bridged-tokens/eth 

**Implementation:**
[backend task](https://github.com/orgs/blockscout/projects/8/views/1?filterQuery=nik&pane=issue&itemId=38249619)

**Comment by tgladilina** [comment]
@ulyanas let's discuss it 

![Image](https://github.com/blockscout/frontend/assets/103045386/d653785a-7dfe-4396-bee4-c32bdf272aca)
![Image](https://github.com/blockscout/frontend/assets/103045386/fc3c3051-d1e9-45ef-a12f-5a28007c235a)
![Image](https://github.com/blockscout/frontend/assets/103045386/539d2ced-59ca-4ae0-ac5b-822b352985db)

**Figma** 
https://www.figma.com/file/4In0X8UADoZaTfZ34HaZ3K/Blockscout_2.0?type=design&node-id=2673-71364&mode=design&t=bgXVYbncbm3cgbM7-4

**Comment by tgladilina** [comment]
**Updated**

**All tokens page** 

<img width="802" alt="Screenshot 2023-10-02 at 12 53 23" src="https://github.com/blockscout/frontend/assets/103045386/71b16f4e-9502-49f9-98d4-5c436a317611">

Tab "Bridged" + mobile view 

<img width="1029" alt="Screenshot 2023-10-02 at 12 53 35" src="https://github.com/blockscout/frontend/assets/103045386/844769f1-a16f-4d1d-a953-e2142d9511eb">

**Figma**
https://www.figma.com/file/4In0X8UADoZaTfZ34HaZ3K/Blockscout_2.0?type=design&node-id=2673-71208&mode=design&t=HFwXQv5h0zpJlbp7-4

@tom2drum cc

**Comment by tom2drum** [comment]
ENV variables example for UI customization

```
NEXT_PUBLIC_BRIDGED_TOKENS_CHAINS=[{'id':'1','title':'Ethereum','short_title':'ETH','base_url':'https://eth.blockscout.com/token/'},{'id':'56','title':'Binance Smart Chain','short_title':'BSC','base_url':'https://bscscan.com/token/'},{'id':'99','title':'POA','short_title':'POA','base_url':'https://blockscout.com/poa/core/token/'}]
NEXT_PUBLIC_BRIDGED_TOKENS_BRIDGES=[{'type':'omni','title':'OmniBridge','short_title':'OMNI'},{'type':'amb','title':'Arbitrary Message Bridge','short_title':'AMB'}]
```
