### ISSUE TITLE
Use market_cap property in the response of stats/charts/market, if available_supply is zero

### ISSUE THREAD

**Issue by vbaranov** [blockscout/frontend#1170]
### Description

Currently, it is unused and leads to zeros on the market cap chart.

![Screenshot 2023-09-12 at 11 12 49](https://github.com/blockscout/frontend/assets/4341812/a5c02589-0637-4a64-8875-cfe0c7758a91)

https://www.shibariumscan.io/api/v2/stats/charts/market

```
{"available_supply":0,"chart_data":[{"closing_price":"0.813819","date":"2023-09-12","market_cap":"186869783"},{"closing_price":"0.911506","date":"2023-09-11","market_cap":"209338820"},{"closing_price":"0.937772","date":"2023-09-10","market_cap":"216179427"},{"closing_price":"0.920589","date":"2023-09-09","market_cap":"212230612"},{"closing_price":"0.966646","date":"2023-09-08","market_cap":"222215156"},{"closing_price":"0.959002","date":"2023-09-07","market_cap":"221834776"},{"closing_price":"1.008","date":"2023-09-06","market_cap":"231954554"},{"closing_price":"1.018","date":"2023-09-05","market_cap":"234074505"}]}
```

### Link to the page

https://www.shibariumscan.io/

### Steps to reproduce

1. Go to https://www.shibariumscan.io/
2. Click on "Market cap" chart view
3. Chart shows zeros

### App version

v1.10.0

### Operating system

None

**Comment by isstuev** [comment]
@vbaranov can you remind, why not use the "market_cap" property in all cases, since we have that data?
