### ISSUE TITLE
Wrong contract read bytes32[]

### ISSUE THREAD

**Issue by cauta** [blockscout/frontend#1176]
### Description

when i retrieve parition in contract `0x0732d84cF7ed9161eAc09236045dAa8cba2B54C8`  with input `0x627306090abaB3A6e1400e9345bC60c78a8BEf57` i expect:
<img width="291" alt="image" src="https://github.com/blockscout/frontend/assets/15400058/30fd760b-0125-4c1a-ad6b-fd95757d38fa">

but it returned:
<img width="1241" alt="image" src="https://github.com/blockscout/frontend/assets/15400058/d65e633a-39dd-48ce-a88b-a933d13e5da2">

### Link to the page

http://dev1.crypitor.com/address/0x0732d84cF7ed9161eAc09236045dAa8cba2B54C8?tab=read_contract

### Steps to reproduce

1. Go to '23 partitionOf'
2. Click on 'Query'
3. See output:
```
[ partitionsOf method response ]

[

  bytes32[]: 0x307837323635373336353732373636353634303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030,0x307836393733373337353635363430303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030

]
```

4. function `25. totalPartitions` also error:
```
(bytes32[]): undefined
```

expected:
```

bytes32[]: 0x7265736572766564000000000000000000000000000000000000000000000000,0x6973737565640000000000000000000000000000000000000000000000000000

```

### App version

Backend: v5.2.2-beta.+commit.c9f5eee4  Frontend: v1.10.0+ea5c9d58

### Browser

Version 116.0.5845.179 (Official Build) (arm64)

### Operating system

macOS

**Comment by cauta** [comment]
i upgraded to new version 5.2.3. the function with query button working as expected. but the auto query function return undefined. you can take a look at function `totalPartitions` i had mentioned above

**Comment by cauta** [comment]
@nikitosing please check it again, 
i'm still facing error in decoding response with function with auto query

**Comment by nikitosing** [comment]
@tom2drum Could you please check. Back returns read function result. 
https://dev1.crypitor.com/address/0x0732d84cF7ed9161eAc09236045dAa8cba2B54C8?tab=read_contract
<img width="676" alt="image" src="https://github.com/blockscout/frontend/assets/32202610/0abecc4c-29f6-44fe-a886-917be07e6466">

**Comment by cauta** [comment]
Seem like it's fixed. when will the next version release guys?
