### ISSUE TITLE
Add possibility to separate coin display name for the price chart on the main page and display name of the native coin.

### ISSUE THREAD

**Issue by vbaranov** [blockscout/frontend#1177]
### Description

For chains with dual tokens model like Gnosis chain where native token is xDai and governance token is GNO, it is make sense to use native token in the transactions/addresses etc, but display price and market cap of the governance token.

It seems, we need a separate env variable for coin display name on the price/market cap charts with the fallback to the value from NEXT_PUBLIC_NETWORK_CURRENCY_NAME.

### Link to the page

https://gnosis.blockscout.com

### App version

v1.10.0

### Operating system

None

**Comment by isstuev** [comment]
added NEXT_PUBLIC_NETWORK_GOVERNANCE_TOKEN_SYMBOL variable
it is used only for the main page price chart
