### ISSUE TITLE
Latest blocks layout issue

### ISSUE THREAD

**Issue by nnlgsakib** [blockscout/frontend#1189]
### Description

![Screenshot_2023-09-16-20-41-49-87_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/blockscout/frontend/assets/107909889/9b8162b6-dc7d-45ba-bcc4-5fd0f731ce6e)

validator addr is  crossing the block box

### Link to the page

https://mainnet.mindscan.info

### Steps to reproduce

You can check it at homepage 

### App version

v1.2.0

### Operating system

None

**Comment by tom2drum** [comment]
Can you share the list of ENV variable values that are used for running the app? And also could you update the app version to the latest one?

**Comment by ekawibisono** [comment]
Hi bro @nnlgsakib 
I think you have to check your backend, does your backend block also display the address 0x000000000000000000000 ?

**Comment by nnlgsakib** [comment]
> Hi bro @nnlgsakib I think you have to check your backend, does your backend block also display the address 0x000000000000000000000 ?

No 


BS v1 : http://v2.mindscan.info:3000/

**Comment by nnlgsakib** [comment]
> Can you share the list of ENV variable values that are used for running the app? And also could you update the app version to the latest one?

Yes I have updated to the latest version and 

my env vars https://raw.githubusercontent.com/nnlgsakib/Example-/main/.env.

**Comment by nnlgsakib** [comment]
> > Can you share the list of ENV variable values that are used for running the app? And also could you update the app version to the latest one?
> 
> Yes I have updated to the latest version and
> 
> my env vars https://raw.githubusercontent.com/nnlgsakib/media/main/.env.

**Comment by ekawibisono** [comment]
> > Hi bro @nnlgsakib I think you have to check your backend, does your backend block also display the address 0x000000000000000000000 ?
> 
> No
> 
> BS v1 : http://v2.mindscan.info:3000/

in your backend, address miner or validator not show
![image](https://github.com/blockscout/frontend/assets/22586872/acd167cc-8153-48fd-905f-96e29bed6536)

in your env backend, BLOCK_TRANSFORMER your setting what ? base or clique ?

**Comment by tom2drum** [comment]
> my env vars https://raw.githubusercontent.com/nnlgsakib/media/main/.env

@nnlgsakib thanks. Confirm, that is a bug, we will try to fix it in the next release. Stay tuned.

**Comment by nnlgsakib** [comment]
> > my env vars https://raw.githubusercontent.com/nnlgsakib/media/main/.env
> 
> @nnlgsakib thanks. Confirm, that is a bug, we will try to fix it in the next release. Stay tuned.



> > my env vars https://raw.githubusercontent.com/nnlgsakib/media/main/.env
> 
> @nnlgsakib thanks. Confirm, that is a bug, we will try to fix it in the next release. Stay tuned.

NEXT_PUBLIC_VIEWS_BLOCK_HIDDEN_FIELDS=["burnt_fees","total_reward"]

I noticed that after removing this env var everything is back to normal. That means there is a problem here

**Comment by nnlgsakib** [comment]
> > my env vars https://raw.githubusercontent.com/nnlgsakib/media/main/.env
> 
> @nnlgsakib thanks. Confirm, that is a bug, we will try to fix it in the next release. Stay tuned.

NEXT_PUBLIC_VIEWS_BLOCK_HIDDEN_FIELDS=["burnt_fees","total_reward"]

I noticed that after removing this env var everything is back to normal. That means there is a problem here

**Comment by nnlgsakib** [comment]
> > > Hi bro @nnlgsakib I think you have to check your backend, does your backend block also display the address 0x000000000000000000000 ?
> > 
> > 
> > No
> > BS v1 : http://v2.mindscan.info:3000/
> 
> in your backend, address miner or validator not show ![image](https://user-images.githubusercontent.com/22586872/269280774-acd167cc-8153-48fd-905f-96e29bed6536.png)
> 
> in your env backend, BLOCK_TRANSFORMER your setting what ? base or clique ?

Base!

**Comment by ekawibisono** [comment]
I Think not bug, check this i build frontend and show address. @tom2drum @nnlgsakib 

![image](https://github.com/blockscout/frontend/assets/22586872/3fb72f63-e64f-4a2c-9684-47dcb5d1604e)

**Comment by nnlgsakib** [comment]
> I Think not bug, check this i build frontend and show address. @tom2drum @nnlgsakib
> 
> i think in your backend update env this BLOCK_TRANSFORMER=base to BLOCK_TRANSFORMER=clique
> 
> But what client node are you using? @nnlgsakib
> 
> ![image](https://user-images.githubusercontent.com/22586872/269334649-3fb72f63-e64f-4a2c-9684-47dcb5d1604e.png)

https://github.com/blockscout/frontend/issues/1189#issuecomment-1727911611

**Comment by nnlgsakib** [comment]
> I Think not bug, check this i build frontend and show address. @tom2drum @nnlgsakib
> 
> i think in your backend update env this BLOCK_TRANSFORMER=base to BLOCK_TRANSFORMER=clique
> 
> But what client node are you using? @nnlgsakib
> 
> ![image](https://user-images.githubusercontent.com/22586872/269334649-3fb72f63-e64f-4a2c-9684-47dcb5d1604e.png)

https://github.com/blockscout/frontend/issues/1189#issuecomment-1727911611

**Comment by ekawibisono** [comment]
> > I Think not bug, check this i build frontend and show address. @tom2drum @nnlgsakib
> > i think in your backend update env this BLOCK_TRANSFORMER=base to BLOCK_TRANSFORMER=clique
> > But what client node are you using? @nnlgsakib
> 
> using polygon-edge
> 
> and its a bug please check it [#1189 (comment)](https://github.com/blockscout/frontend/issues/1189#issuecomment-1727911611)

![image](https://github.com/blockscout/frontend/assets/22586872/b86ad7d5-734b-4928-bdc4-52b3ee3310cb)

i think bug on NEXT_PUBLIC_VIEWS_BLOCK_HIDDEN_FIELDS=['burnt_fees','total_reward']

but i add again NEXT_PUBLIC_VIEWS_BLOCK_HIDDEN_FIELDS=['burnt_fees','total_reward','nonce'] result from image

**Comment by ekawibisono** [comment]
I don't think this is a bug, maybe you didn't add enough 'nonce'. But back to team blockscout, whether it's a bug or not.

**Comment by tom2drum** [comment]
I definitely see the problem with the layout in some scenarios. So it is a bug.

**Comment by ekawibisono** [comment]
> I definitely see the problem with the layout in some scenarios. So it is a bug.

Maybe the problem is on the part of the Special Hidden Block
