### ISSUE TITLE
Token icon image: add 50% border radius

### ISSUE THREAD

**Issue by tom2drum** [blockscout/frontend#1197]
Since most of the imported images are circles, lets round up the token image container, to hide unnecessary backgrounds:

Now:
![Image](https://user-images.githubusercontent.com/1701762/269273426-e77fa22b-293a-4477-a24b-fb19b19ea9f8.png)

-> 
To be: 
![Image](https://user-images.githubusercontent.com/1701762/269273515-e980942f-8028-41d0-abf3-faaa8e2ca598.png)

**Comment by tgladilina** [comment]
> @NikitaSavik @tgladilina is this rule for all places where we display token icon or only for the page title? token icon placeholder should be rounded as well?
> 
> can we do these changes on mock-ups too then?

The original token icon can be any shape inside our frame with 2px corner radius without background

<img width="1083" alt="Screenshot 2023-09-20 at 17 14 57" src="https://github.com/blockscout/frontend/assets/103045386/7dc36dd0-27b7-42cd-90cd-18593a7fafb0">
