### ISSUE TITLE
API v2 sandbox doesn't account the value in NEXT_PUBLIC_API_PROTOCOL

### ISSUE THREAD

**Issue by vbaranov** [blockscout/frontend#1203]
### Description

Despite setting NEXT_PUBLIC_API_PROTOCOL=http, requests to the API from every endpoint from /api-docs page will still be made to https, for instance:
https://localhost/api/v2/transactions.
Instead request should go to http://localhost/api/v2/transactions.

### Link to the page

http://localhost

### Steps to reproduce

1. git clone https://github.com/blockscout/blockscout
2. cd blockscout/docker-compose/
3. docker-compose up
4. open http://localhost
5. open API -> REST API in the menu
6. Execute any of the endpoint, e.g. /transactions

### App version

v.1.11.1

### Operating system

None

**Comment by suzhongping** [comment]
NEXT_PUBLIC_API_HOST not work too
