### ISSUE TITLE
Change issue template when submitting issue from the footer

### ISSUE THREAD

**Issue by vbaranov** [blockscout/frontend#1227]
### Description

Currently, this one is used from the footer of the application:

https://github.com/blockscout/blockscout/issues/new/?labels=new+UI&title=Ethereum%3A+%3CIssue+Title%3E&body=%0A*Describe+your+issue+here.*%0A%0A%23%23%23+Environment%0A%0A*+Backend+Version%2Fbranch%2Fcommit%3A+v5.2.3-beta.%2Bcommit.382fdee4%0A*+Frontend+Version%2Bcommit%3A+v1.11.1%2B49c5e3fa%0A*+User+Agent%3A+Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_15_7%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F117.0.0.0+Safari%2F537.36%0A%0A%23%23%23+Steps+to+reproduce%0A%0A*Tell+us+how+to+reproduce+this+issue.++%E2%9D%A4%EF%B8%8F+if+you+can+push+up+a+branch+to+your+fork+with+a+regression+test+we+can+run+to+reproduce+locally.*%0A%0A%23%23%23+Expected+behaviour%0A%0A*Tell+us+what+should+happen.*%0A%0A%23%23%23+Actual+behaviour%0A%0A*Tell+us+what+happens+instead.*%0A++++

Recently `bug_report.yaml` has been added. Please, use it instead.
Here is an example of filling the template, that could be used from the frontend app:
https://github.com/blockscout/blockscout/issues/new?template=bug_report.yml&labels=triage&backend-version=v5.2.1-beta&frontend-version=1.12.0&additional-information=The+issue+happened+at+Gnosis+Chain+Chiado+Blockscout+instance

### Link to the page

https://eth.blockscout.com/

### App version

v1.11.1

### Operating system

None

**Comment by tom2drum** [comment]
Does a regular user know "Type of the installation", "Type of the JSON RPC archive node", "Elixir & Erlang/OTP versions"?. I suggest that those shouldn't be required fields.
