### ISSUE TITLE
Address > NFT improvements

### ISSUE THREAD

**Issue by ulyanas** [blockscout/frontend#1245]
Waiting for https://github.com/blockscout/blockscout/issues/8231
[PR](https://github.com/blockscout/blockscout/pull/8634)

**1st iteration:** 

-  without filter by collection
-  two tabs: ERC-20 and NFTs

![Image](https://github.com/blockscout/frontend/assets/103045386/b782578b-a9b0-4df9-adaa-ee49bb486345)

-  "Collection" view by default
- "View in token collection" goes to collection page filtered by address
-  you can filter by token type (ERC-721, ERC-1155)
-  Preview of 9 items and "View all NFTs" link to collection page filtered by address

![Image](https://github.com/blockscout/frontend/assets/103045386/6756effa-cc29-4357-bd8a-696397174d6c)

![Image](https://github.com/blockscout/frontend/assets/103045386/0d796c35-de57-49b8-bfde-626394ffbc85)

![Image](https://github.com/blockscout/frontend/assets/103045386/8d7325c8-18be-4518-8095-1265d774983f)

-  ERC-1155 with qty

![Image](https://github.com/blockscout/frontend/assets/103045386/6e85863b-c3b8-4434-a9c3-08a78227bfed)

**Figma** 
https://www.notion.so/blockscout/Design-For-Collections-view-7b7ac288884a4dbda78101363af8683f?pvs=4

https://www.figma.com/file/4In0X8UADoZaTfZ34HaZ3K/Blockscout_2.0?type=design&node-id=14498-45626&mode=design

**Comment by isstuev** [comment]
add redirects from old tabs urls

**Comment by isstuev** [comment]
token balances ws???

**Comment by NikitaSavik** [comment]
Waiting for [backend PR](https://github.com/blockscout/blockscout/pull/8634) review

**Comment by ulyanas** [comment]
Update: waiting for the backend release
