### ISSUE TITLE
Introduce new ENV to allow hiding of certain fields in transactions

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#1247]
e.g. for Shimmer, we want to hide 'Transaction fee' and 'Gas price'

**Comment by tom2drum** [comment]
DOCs - https://github.com/blockscout/frontend/blob/main/docs/ENVS.md#transaction-views

ENV example
`NEXT_PUBLIC_VIEWS_TX_HIDDEN_FIELDS=['gas_price','tx_fee']`

cc @NikitaSavik
