### ISSUE TITLE
It is hard to find verification button for partially verified contracts

### ISSUE THREAD

**Issue by vbaranov** [blockscout/frontend#1251]
### Description

I would expect button somewhere here:
![Screenshot 2023-10-04 at 15 15 14](https://github.com/blockscout/frontend/assets/4341812/07227a7e-afb8-4c17-8a50-cf1bce36bdb2)

Likely, inside the warning`This contract has been partially verified using 
[Blockscout Bytecode Database](https://docs.blockscout.com/about/features/ethereum-bytecode-database-microservice)`.

Perhaps, it'd be handful to duplicate the button in this warning?

### Link to the page

https://gnosis-chiado.blockscout.com/address/0x17d9873e3A5de82d3185AaB5a91749672B58f104?tab=contract

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### App version

v1.12.0

### Operating system

None

**Comment by tgladilina** [comment]
@vbaranov please review options

**1st option** 
<img width="1178" alt="Screenshot 2023-10-13 at 16 41 04" src="https://github.com/blockscout/frontend/assets/103045386/1c1a9e88-a2ce-4fab-8fcf-1ed4d7e75894">

**2nd variant**  to combine message and add button
<img width="1176" alt="Screenshot 2023-10-13 at 16 41 09" src="https://github.com/blockscout/frontend/assets/103045386/d650a033-2def-49bc-9afa-f4c5344dcf42">

**p.s. Please remove CAPS from secondary words:**
Contract Source Code Verified (Partial Match) > Contract source code verified (Partial match)
This contract has been partially verified using Blockscout Bytecode Database > This contract has been partially verified using Blockscout bytecode database

**Comment by tom2drum** [comment]
Like the first option

**Comment by NikitaSavik** [comment]
going with the 1st option, but the button is going to the first alert (Contract source code...)
