### ISSUE TITLE
Tx logs: "Contract must be verified" message shown for the already verified contract in Tx logs

### ISSUE THREAD

**Issue by ulyanas** [blockscout/frontend#1268]
https://eth.blockscout.com/tx/0x5ad65dfa90672c50d44d1e44f0db545fb337aa3da9656a5768ec163caa9d3dd5?tab=logs 

"Contract must be verified" message shown for the already verified contract in Tx logs. 

![Image](https://github.com/blockscout/frontend/assets/6618204/e9ec1c96-5fd3-4458-abfc-10985a9c9296)

**Steps:**
1) Open logs for a tx with unverified contract
2) Verify the contract
3) Open logs again 

**Result:**
- "Contract must be verified" message shown for the already verified contract in Tx logs. 
- Data is not decoded

**Should be:**
Logs should be decoded for a tx involving verified contracts

**Comment by isstuev** [comment]
the decoded status was taken from the API response, all the records except the first one have "decoded: null" property, what to show in that case?
