### ISSUE TITLE
Stability UI customizations V0

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#1269]
For Stability network, substantial amount of info should be removed from the UI.

- [ ] Hide 'Top ~~contracts~~ accounts'
- [ ] Tx list > Hide “Value ETH” column
- [ ] Tx details page (remove fields from spec)

Full description:
https://www.notion.so/blockscout/Stability-features-226ce2d687fd40ee9f98031733d5feb2?pvs=4

**Comment by tom2drum** [comment]
"Tx list > Replace “Fee ETH” to “Fee”" - for could be achieved by not providing `NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL` variable

**Comment by tom2drum** [comment]
**ENV values**

```
NEXT_PUBLIC_VIEWS_ADDRESS_HIDDEN_VIEWS: "['top_accounts']"
NEXT_PUBLIC_VIEWS_TX_HIDDEN_FIELDS: "['value','fee_currency','gas_price','gas_fees','burnt_fees']"
NEXT_PUBLIC_VIEWS_TX_ADDITIONAL_FIELDS: "['fee_per_gas']"

```
