### ISSUE TITLE
Support stats widget for Rootstock

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#1271]
Backend: https://github.com/blockscout/blockscout/pull/8583

Example of a response from `api/v2/stats`:
```json
{
    "average_block_time": 32093.0,
    "coin_price": "1648.69",
    "gas_prices": null,
    "gas_used_today": "0",
    "market_cap": "0",
    "network_utilization_percentage": 4.397353529411765,
    "rootstock_locked_btc": "3362966539366688755390",
    "static_gas_price": null,
    "total_addresses": "225",
    "total_blocks": "142",
    "total_gas_used": "0",
    "total_transactions": "530",
    "transactions_today": "0"
}
```

**Field value is in wei**

UI reference:
![Image](https://user-images.githubusercontent.com/1701762/267058476-5a3395b6-dc37-417e-95b9-7c3f633f2515.png)

**Note that `rootstock_locked_btc` field is optional**
It won't appear on non-rootstock chains and in case if we do not have data on the backend for any reason

**Comment by tom2drum** [comment]
@NikitaSavik what icon should we use for this snippet? can you provide mock-ups?

The title will be "BTC Locked in 2WP", am I correct?

**Comment by NikitaSavik** [comment]
![bitcoin](https://github.com/blockscout/frontend/assets/1701762/d82aa61a-89a9-40e0-93b5-bcbe39c725ec)
yes, Title is "BTC Locked in 2WP"

**Comment by NikitaSavik** [comment]
PR merged: https://github.com/blockscout/blockscout/pull/8583
API on mainnet: https://rootstock.blockscout.com/api/v2/stats
