### ISSUE TITLE
Filter counter

### ISSUE THREAD

**Issue by tgladilina** [blockscout/frontend#1291]
**Doesn't work now**

![Image](https://github.com/blockscout/frontend/assets/103045386/1197d08f-4ac4-4a5a-a699-533b10a4cff9)

**Correct** 

![Image](https://github.com/blockscout/frontend/assets/103045386/a9588c5d-5e46-403d-9db5-bbeb497052ff)

**Comment by NikitaSavik** [comment]
+fix at Address-Transactions tab
