### ISSUE TITLE
No way to input compiler version when verifying contract

### ISSUE THREAD

**Issue by oxSaturn** [blockscout/frontend#1303]
### Description

I can't select or input compiler version when verifying contract.

### Link to the page

https://optimism.blockscout.com/address/0x6CFDAc4A1F9DF334DB8DcCfDA2FB62b46F705582/contract-verification

### Steps to reproduce

1. Go to https://optimism.blockscout.com/address/0x6CFDAc4A1F9DF334DB8DcCfDA2FB62b46F705582/contract-verification
2. select verification method

![CleanShot-UBDtE0BB@2x](https://github.com/blockscout/frontend/assets/126733611/83477d83-0098-40cb-b3da-109bf672f3ec)

now try to select or input the compiler version.

### App version

v1.15.0

### Browser

edge

### Operating system

macOS

### Additional information

I can reproduce it on many blockscout app, like the one above, or canto's tuber.build.

**Comment by tom2drum** [comment]
Works fine for me. If there are no compiler options to choose from, it's very likely a problem on the API side, since the front app gets the compilers list from there. So, I will transfer this issue to the main BS repo.

![Image](https://github.com/blockscout/frontend/assets/22130104/8edb63f0-c388-42c5-90a2-5c8b4d24a31a)

**Comment by oxSaturn** [comment]
hmm, yeah, seems it loads now for me on op, but still not working on canto https://tuber.build/address/0xcA11bde05977b3631167028862bE2a173976CA11/contract-verification:

![CleanShot-SC3v7cUt@2x](https://github.com/blockscout/frontend/assets/126733611/2eca7290-6688-496a-b1ed-5ee4c49645d7)

**Comment by tom2drum** [comment]
I believe something is wrong with the API configuration. This instance is not run by Blockscout team, so please ask for help on our official Discord channel. This should not be solved as an issue in GitHub.
