### ISSUE TITLE
Expand action of NEXT_PUBLIC_HIDE_INDEXING_ALERT to the indexing banner at the top

### ISSUE THREAD

**Issue by vbaranov** [blockscout/frontend#1307]
### Description

Currently, its action is limied to the indexing alert in the footer.

### Link to the page

https://eth.blockscout.com/

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### App version

v1.15.0

### Operating system

None

**Comment by tom2drum** [comment]
@vbaranov I will replace current variable `NEXT_PUBLIC_HIDE_INDEXING_ALERT` with two then, one for each alert -`NEXT_PUBLIC_HIDE_INDEXING_ALERT_BLOCKS` and `NEXT_PUBLIC_HIDE_INDEXING_ALERT_INT_TXS`

ok?
