### ISSUE TITLE
L2 Chain Based Optimism Can't Running

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/frontend#1309]
### Description

Cannot running Blockscout used L2 Based Optimism, but unset the L2 Environment is perfectly running, 
[Documentation](https://stack.optimism.io/docs/build/explorer/#archive-mode) Optimism Running Blockscout need `--gcmode=archive` is already setting to start node. Now Blockscout running without Env Var L2 

RPC Expose on Public : 
```
<IPAddress:8545> op-geth
<IPAddress:8547> op-node
<IPAddress:8560> op-proposer
<IPAddress:8548> op-batcher
```

ENV Frontend : 
```
# Optimistic rollup (L2) chain
NEXT_PUBLIC_IS_OPTIMISTIC_L2_NETWORK=true
NEXT_PUBLIC_OPTIMISTIC_L2_WITHDRAWAL_URL=https://app.optimism.io/bridge/withdraw
NEXT_PUBLIC_L1_BASE_URL=https://sepolia.etherscan.io
```

Logs Frontend : 
```
🌀 Checking environment variables and their placeholders congruity...
🚸 For the following environment variables placeholders were not generated at build-time:

 NEXT_PUBLIC_OPTIMISTIC_L2_WITHDRAWAL_URL
 NEXT_PUBLIC_IS_OPTIMISTIC_L2_NETWORK

 They are either deprecated or running the app with them may lead to unexpected behavior. 
 Please check the documentation for more details - https://github.com/blockscout/frontend/blob/main/docs/ENVS.md
      
🚨 Congruity check failed.
```

### Link to the page

https://cybascan.io

### Steps to reproduce

1. Go to 'blockscout/docker-compose'
2. Click on 'customize docker-compose-no-build-geth.yml with RPC Public L2'
3. See error 'docker ps'

`ghcr.io/blockscout/frontend:latest "./entrypoint.sh nod…" 10 minutes ago Restarting (1) 40 seconds`

### App version

latest

### Browser

Version 118.0.5993.88 (Official Build) (64-bit)

### Operating system

Linux

**Comment by avenbreaks** [comment]
@tom2drum

**Comment by tom2drum** [comment]
Please note that the current names of the variables is `NEXT_PUBLIC_IS_L2_NETWORK` and `NEXT_PUBLIC_L2_WITHDRAWAL_URL`.

https://github.com/blockscout/frontend/blob/v1.16.0/docs/ENVS.md#rollup-l2-chain

We are renaming only in the next release.
