### ISSUE TITLE
Missing envs.js in public folder

### ISSUE THREAD

**Issue by sakthikutti21** [blockscout/frontend#1310]
### Description

when trying to run this code i got issue (TypeError: Cannot read properties of undefined (reading 'NEXT_PUBLIC_APP_INSTANCE')).
And also i find envs.js is missing in public folder. i am beginners to set up this project, please explain me in detail

### Link to the page

localhost

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### App version

latest

### Browser

Version 118.0.5993.118 (Official Build) (64-bit)

### Operating system

Windows

**Comment by tom2drum** [comment]
Please indicate the exact version of the front-end app you are running.

**Comment by sakthikutti21** [comment]
> Please indicate the exact version of the front-end app you are running.

App version   v1.16.0

**Comment by sakthikutti21** [comment]
How to set up env file

**Comment by tom2drum** [comment]
How do you run the app? This file is automatically generated when the app is started.

**Comment by arief-snap** [comment]
same here on version 1.32.1

Refused to execute script from 'http://localhost:3000/assets/envs.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

the envs was notfound

http://localhost:3000/assets/envs.js

tried on linux and windows same result
