### ISSUE TITLE
How to take build

### ISSUE THREAD

**Issue by sakthikutti21** [blockscout/frontend#1316]
### Description

How to take build and deploy in live aws server using plesk tool.

we tried to take build using following.
-> npm run build:docker
first build is running, After build completed i am getting below error
Error: 
What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview

### Link to the page

localhost

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### App version

v1.0.0

### Operating system

macOS

**Comment by tom2drum** [comment]
Are you following this [guide](https://github.com/blockscout/frontend/blob/main/docs/CUSTOM_BUILD.md)?

Please ask for support in GitHub discussions or in our Discord channel. I believe GitHub issues are not meant for this.
