### ISSUE TITLE
CredShields: show trust score

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#1371]
Todo:

- small widget with credit score
- - < 30 - red, low
- - 30 < x < 80, orange, average
- - > 80, green, great
- pop-over with detailed information returned from API (amounts of vulenrabilities) + link to quickScan 

Links:
[API specs](https://apidoc.solidityscan.com/solidityscan-security-api/solidityscan-other-apis/quickscan-api-v1)
[Design task](https://www.notion.so/4744fa349974493dab27f527795b256f?pvs=25)
[Figma](https://www.figma.com/file/4In0X8UADoZaTfZ34HaZ3K/Blockscout_2.0?type=design&node-id=15393-98948&mode=design&t=xzVFQw1ASS83HWTr-0)
[Proxy method task](https://github.com/orgs/blockscout/projects/8/views/1?filterQuery=cred&pane=issue&itemId=45536992)

**Comment by isstuev** [comment]
set NEXT_PUBLIC_VIEWS_CONTRACT_SOLIDITYSCAN_ENABLED to `true` to enable this feature
