### ISSUE TITLE
'Blocks validated' tab is absent on Stability

### ISSUE THREAD

**Issue by yvaskov** [blockscout/frontend#1379]
## Description

There is no 'Blocks validated' tab on 'Address details' page on Stability:
https://stability-testnet.blockscout.com/address/0xfC33837428cf3d6aC7E8C05c6806A730FbdC8fd2

![Image](https://github.com/blockscout/frontend/assets/72267126/12452382-6d8d-4497-a4eb-492a6be03aa1)

Backend returns correct counter.

## Version

[v1.17.0](https://github.com/blockscout/frontend/tree/v1.17.0)

**Comment by isstuev** [comment]
NEXT_PUBLIC_NETWORK_VERIFICATION_TYPE = 'validation' is required to show that tab
