### ISSUE TITLE
Backward pagination doesn't work on direct links with page params

### ISSUE THREAD

**Issue by yvaskov** [blockscout/frontend#1388]
## Description

'Prev page' navigation button doesn't become active after switching to the next page from direct link.

![Image](https://github.com/blockscout/frontend/assets/72267126/9d56085a-eed0-4d75-ab28-e8bf7e8941a0)

## Steps to reproduce

1. Open https://eth.blockscout.com/token/0x16de9D750F4AC24226154C40980Ef83d4D3fD4AD?page=4&next_page_params=%257B%2522unique_token%2522%253A4900%257D
2. Click on 'Next page' button

## Actual result

User can't return from page 5 to 4, 6 to 5 and so on. 'Prev page' button is inactive.

## Expected result

User is able to navigate back to the originally opened page (4 in the example above) from any of the following pages.

**Comment by 0xtzData** [comment]
https://eth-goerli.blockscout.com/token/0x9e57f94CD4237f39325DB4b2162A541716921CDF?page=4&next_page_params=%257B%2522block_number%2522%253A9449852%252C%2522index%2522%253A850%257D still need to be fixed in [v1.21.0-alpha.1](https://github.com/blockscout/frontend/tree/v1.21.0-alpha.1)

**Comment by isstuev** [comment]
it will not work on the 4th page in your example (we don't have prev page params), but if you navigate forward -- you will be able to navigate back (from 5th to 4th in your example.) that was the idea of the task
