### ISSUE TITLE
Stats Update

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#1400]
- [ ]  Homepage:
    - [ ]  Add historical OP price to the Homepage
    - [ ]  Add latest L1 state batch size to the Homepage
- [ ]  Add historical OP price to the Stats > Market Data section
- [ ]  Add transactions stats to Blockchain > Transactions page: Txns 24h, Pending txns 24h, Tx fees 24h, Avg txn fee 24h
  
- [ ] Add Volume (24H) to the Token details

[Backend Task](https://github.com/orgs/blockscout/projects/8/views/1?pane=issue&itemId=46887823)
[Full description](https://www.notion.so/blockscout/STAT-New-stats-and-mainpage-counters-e98b9c1640934578a170ffed5a2fb835?pvs=4)

**Comment by tgladilina** [comment]
@NikitaSavik Design task is ready 
https://www.notion.so/blockscout/Design-For-OP-stats-update-c4f3cc5abe22413fa11acf0b4b310c7e?pvs=4

**Comment by NikitaSavik** [comment]
Deployed with 6.3.0

**Comment by NikitaSavik** [comment]
Update released in 6.4
