### ISSUE TITLE
Tooltip for GAS tracker

### ISSUE THREAD

**Issue by tgladilina** [blockscout/frontend#1405]
**Tooltip for :**

- Top line (if we don't have link to gas tracker page and if we have it)

![Image](https://github.com/blockscout/frontend/assets/103045386/e1cea6e1-7f6d-4fd1-8c4f-06c1cdc3876f)

- Home page (stats section)

![Image](https://github.com/blockscout/frontend/assets/103045386/6abd2548-2b1a-464f-9808-881d358d97a6)

- Charts & stats

![Image](https://github.com/blockscout/frontend/assets/103045386/1416f620-c85a-419f-bf69-0b6467f35d41)

**Comment by tom2drum** [comment]
back-end task - https://github.com/blockscout/blockscout/issues/8833
