### ISSUE TITLE
Closing keyboard while searching hides search result on iOS

### ISSUE THREAD

**Issue by yvaskov** [blockscout/frontend#1411]
## Description

Clicking 'Done' on iOS keyboard while searching hides both keyboard and search results.

## Version

[v1.19.0](https://github.com/blockscout/frontend/tree/v1.19.0)

**Comment by isstuev** [comment]
I found one more bug here (probably connected with the release of our new top bar)
The first search input tap initiates focus, then scroll, and that scroll causes focus loss. 
If scroll and then tap, everything works right.
