### ISSUE TITLE
Add the banner for connect wallet button

### ISSUE THREAD

**Issue by maikReal** [blockscout/frontend#1431]
## What to do?

If a user opens an app on the marketplace, we need to show him a banner with information to connect a wallet 

**Copies:** "Connect your wallet once to use it with all dApps on the marketplace!" @andogro Can you review pls? 

**Criteria to show:**
1. If a user opens an app and the global wallet is not connected, show the tooltip
2. The tooltip can be closed by clicking on any space 
3. The tooltip will be closed automatically in 3 seconds if a user doesn't interact with the UI
4. Show once for a user on the dapp page. If a user already saw the tooltip, but not inside the dapp, he'll see this tooltip, because it's different

> **Let's also automatically close the banner for users who see the "Connect button" for the first time. The banner's behavior is described in this issue: https://github.com/blockscout/frontend/issues/1270**

![Image](https://github.com/blockscout/frontend/assets/26190360/c8805694-172e-4137-ad8d-7767166631c0)

**Comment by andogro** [comment]
message suggestion "Connect once to use your wallet with all apps in the DAppscout marketplace!"
