### ISSUE TITLE
Validators list

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#1437]
**Validators page** should provide detailed information about the validators of the PoS chains. This page includes:

- summary statistics on validators
- a full list of validators with detailed information about each of them. 

Requirements: https://www.notion.so/blockscout/Validators-Page-999f17d3801e41d1aabf14cf41401e8d?pvs=4

UI: TBD, under review

Backend task: TBD

**Comment by haidarabdillah** [comment]
seem this is great idea sir

**Comment by tgladilina** [comment]
@ulyanas  cc

Figma file https://www.figma.com/file/CEgxqWOzVulwfTUHhs0gUC/%F0%9F%94%A5-RESEARCH%2FDRAFTs?type=design&node-id=991-7306&mode=design

![Image](https://github.com/blockscout/frontend/assets/103045386/818317f2-2726-4056-822f-4b654c62f2de)
