### ISSUE TITLE
Add Hypelabs - ads provider

### ISSUE THREAD

**Issue by maikReal** [blockscout/frontend#1439]
[PRODUCT TASK](https://www.notion.so/blockscout/Hype-Ads-impressions-for-users-3784a51acb4a4b1d9f82ed48e5b7b155?pvs=4)

**SDK docs:** 
https://docs.hypelab.com/publisher-quickstart

**Slugs:**
https://docs.google.com/spreadsheets/d/1phlVjydtUMuGx-mK-w5Wnc-15EbuOfoBcLzgZPpx9vM/edit#gid=0

## What to do?
We need to integrate Hypelabs SDK for ads to the Blockscout. 

> **For now, we want to use only the Ethereum mainnet in the test mode to understand how it works generally** 

There is an ability to pass the wallet address of a user to the provider, so, we need to use this ability. Let's pass a wallet address that was connected to the header 

![Image](https://github.com/blockscout/frontend/assets/26190360/f5d510b4-bbf6-4ce3-8eb2-7d832ca0102b)

**Comment by isstuev** [comment]
the solution doesn't work for us. Hype team suggested allowing "unsafe-eval" in our CSP, I consider that solution unsafe so we're waiting for the fix on their side

**Comment by maikReal** [comment]
**UPD 23.01:** 

- Hype prepared the solution that we already integrated
- Property slug and placement slug will be the same for all instances, so, we don't need to create variables for them

cc @isstuev
