### ISSUE TITLE
ERC-4337 Account Abstraction: UserOp list

### ISSUE THREAD

**Issue by ulyanas** [blockscout/frontend#1445]
📒 Epic: [**ERC-4337**](https://blockscout.notion.site/EIP4337-29184b5bd04e4330ad2860a712e23d90)

📝 Story: **Implement a page that shows  all User operations** 
https://www.notion.so/blockscout/UserOps-list-e5b58455492c4b0a80d7fea1ebf2da41

References:
https://eips.ethereum.org/EIPS/eip-4337
https://www.erc4337.io/docs

**Comment by isstuev** [comment]
need an icon for the menu item

**Comment by tgladilina** [comment]
icon attached
![userOP](https://github.com/blockscout/frontend/assets/103045386/3b2b0316-3570-4f78-998a-639187884bd5)
 

<img width="461" alt="UserOp_menu_sample" src="https://github.com/blockscout/frontend/assets/103045386/2133e605-5c00-43a9-8e33-21dd16aea391">
