### ISSUE TITLE
Highlighted address

### ISSUE THREAD

**Issue by tgladilina** [blockscout/frontend#1446]
**Challenge:** 

1. Quickly finding other tx involving an address
2. Avoiding being tricked by fake addresses with similar front- and back- characters

**Solution:**
Light version: 

- Highlight address
- separate hover area for address and icon
- Skip In the mobile version (hover doesn't work correctly )
-------------------------------------------------------------------------------------

Extended version (Q1 2024)
++ SolidityScan score 
++ holders for contracts or balance for addresses 
++ add to Watch list
++ summary info (mobile version)

-------------------------------------------------------------------------------------

**Mockups for the "Light" version**

https://www.figma.com/file/4In0X8UADoZaTfZ34HaZ3K/Blockscout_2.0?type=design&node-id=517-9808&mode=design&t=rBRHpACbhwCYppK7-4

1.  separate hover area for address and icon

![Image](https://github.com/blockscout/frontend/assets/103045386/6c425388-a2d5-4aeb-a812-602eb9982b1a)

2. List view 

![Image](https://github.com/blockscout/frontend/assets/103045386/f7e77ec2-22f5-42db-939a-dbfb93a4f70f)

3. Themes (light/dim/dark)

![Image](https://github.com/blockscout/frontend/assets/103045386/6c335b06-0ab0-4d4a-90ac-68ca7ca3718b)

**Original task** 
https://www.notion.so/blockscout/Design-For-Highlighted-address-50d32900c48c405f99584fe945dcb574?pvs=4

**Comment by tom2drum** [comment]
applied for all tables:
- latest txs on homepage
- blocks txs
- tx: token transfers tab, internal txs tab, state tab
- address: txs tab, token transfers tab, internal txs tab
- token: token transfers tab, inventory tab
- token instance: token transfers tab
