### ISSUE TITLE
Value/Qty/Delta in USD ($)

### ISSUE THREAD

**Issue by tgladilina** [blockscout/frontend#1449]
**Challenge:** 
Add value in USD to tables

**Location:** 

1. Home page 

- [ ] blocks
![Image](https://github.com/blockscout/frontend/assets/103045386/8d9c2674-55c7-40bf-879b-7c5f97db9421)

- [ ] Transaction
![Image](https://github.com/blockscout/frontend/assets/103045386/ecbf6bcf-10c2-4efe-9d5e-0874e4c5a842)

2. Transactions
- [ ] list

![Image](https://github.com/blockscout/frontend/assets/103045386/fe725356-6028-4cfb-9818-f1b5364aa47a)

![Image](https://github.com/blockscout/frontend/assets/103045386/c3ad376e-0cc3-4b3b-98bc-9706ca9a5456)

3. Blocks
- [ ] list

![Image](https://github.com/blockscout/frontend/assets/103045386/84dbcfb5-6096-4495-9f3d-b7c24c34ee58)

- [ ] 4. Token transfers
- [ ] 5. Contract details
- [ ] 6. Address details
- [ ] 7. Internal txns
- [ ] 8. Coin balance history
![Image](https://github.com/blockscout/frontend/assets/103045386/a96c88bf-7e60-407e-b781-026127308d7f)

- [ ] 9. Blocks validated:
- also round the values
- in one line /row

Details page:
- [ ] 1. Block details
![Image](https://github.com/blockscout/frontend/assets/103045386/cb7a6884-2d83-4066-99a3-fc1b5e37059c)

- [ ] 2. Tx details
![Image](https://github.com/blockscout/frontend/assets/103045386/ca680308-cd01-49d7-8c9c-bba8b29f70c8)

- [x] 3. Address details
![Image](https://github.com/blockscout/frontend/assets/103045386/47d9b126-574e-44c3-b584-d6dcc9280baa)

- [ ] 4. Verified contracts

**Comment by NikitaSavik** [comment]
Issue to be reviewed with Backend and Frontend teams, to re-evaluate the significance of mentioned features
