### ISSUE TITLE
Add "Public RPC” icon

### ISSUE THREAD

**Issue by tgladilina** [blockscout/frontend#1461]
**Now** https://eth.blockscout.com/

![Image](https://github.com/blockscout/frontend/assets/103045386/08477a18-b6cc-43ed-9d8d-5128e73c065c)

**Please add  "Public RPC” icon to the "Other" menu

![Image](https://github.com/blockscout/frontend/assets/103045386/d732cfa7-8503-4a63-a690-0f545390930d)

![Image](https://github.com/blockscout/frontend/assets/103045386/fd96d26a-f352-4962-9113-19067db3d53e)

![Image](https://github.com/blockscout/frontend/assets/103045386/68a1b6fd-3b41-42d5-b2d5-dad1d8d0c42e)

**Comment by tom2drum** [comment]
agreed to remove icon for "verify contract" link
