### ISSUE TITLE
Update: Contract Score

### ISSUE THREAD

**Issue by tgladilina** [blockscout/frontend#1462]
1. please update colors for light and dark themes: 

**Security score is GREAT**
- gray border color for all scores
- green 600 (light) green 400 (dark) 

![Image](https://github.com/blockscout/frontend/assets/103045386/0a6c1998-ae98-467f-b029-7177c5e895b5)

**Security score is LOW**
- gray border color for all scores
- purple 600 (light) purple 400 (dark) 

![Image](https://github.com/blockscout/frontend/assets/103045386/e327354b-ff16-4c38-bec3-f51000cee221)

**Security score is Critical**
- gray border color for all scores
- red 600 (light) red 400 (dark) 

![Image](https://github.com/blockscout/frontend/assets/103045386/71f4d7ec-a6d9-43de-aa50-69a7407e3247)

2. Could we show the loader for a score? 

![Image](https://github.com/blockscout/frontend/assets/103045386/34a83cc3-5ecb-4a1f-b8af-79a48afe4d83)

**Figma file:**
https://www.figma.com/file/4In0X8UADoZaTfZ34HaZ3K/Blockscout_2.0?type=design&node-id=15393-98948&mode=design

**Comment by isstuev** [comment]
3 - we don't know if a contract has a score or not, so if we replace our skeleton with that loader -- idk how to process the case with empty response or method error
