### ISSUE TITLE
Re-work marketplace filters

### ISSUE THREAD

**Issue by maikReal** [blockscout/frontend#1499]
🦄 **[PRODUCT TASK](https://www.notion.so/blockscout/Restructure-filters-6b30210358244c2b989aed406f8d9da8?pvs=4)**

## What to do?

Based on the users' feedback we need to re-work our filters: make them more detailed and usable

All information can be found in the Product Task

**IMPORTANT ASPECTS:**
1. This task should be launched as an AB experiment with the following tasks:
    - https://github.com/blockscout/frontend/issues/1498
    - https://github.com/blockscout/frontend/issues/1496
    **[All information about the experiment](https://www.notion.so/blockscout/Experiment-1-858bd18b6207478481add09d189ce9e6?pvs=4)**

Cheatsheet about AB test: https://www.notion.so/blockscout/AB-testing-fafb7ad113c14eaeb742fadd8032e4b0?pvs=4

**Comment by maxaleks** [comment]
PR: https://github.com/blockscout/frontend/pull/1543
