### ISSUE TITLE
"Open in IDE" button for contracts

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#1508]
Add new button "Open in IDE" on contract tab
URL example: https://remix.blockscout.com/#address=**{HASH}**&blockscout=**{URL}** with 
[Live test](https://remix.blockscout.com/#address=0x13b0D85CcB8bf860b6b79AF3029fCA081AE9beF2&blockscout=base.blockscout.com)
where HASH is address hash
and URL is the domain of Blockscout instance (e.g. base.blockscout.com)

Notion task: https://www.notion.so/blockscout/VS4-Contract-Source-Code-Open-in-IDE-6a73d9da894b476499e11199330d2d2b?pvs=4
Design: https://www.notion.so/blockscout/Design-For-Contract-Verification-and-data-b84edc5b1c474542bc25bdc3ee65668f?pvs=4

**Comment by tom2drum** [comment]
ENV example value (for Remix):
`NEXT_PUBLIC_CONTRACT_CODE_IDES=[{'title':'Remix IDE','url':'https://remix.blockscout.com/%23address={hash}&blockscout={domain}','icon_url':'https://raw.githubusercontent.com/blockscout/frontend-configs/main/configs/ide-icons/remix.png'}]`
