### ISSUE TITLE
Connect wallet event sent twice

### ISSUE THREAD

**Issue by maikReal** [blockscout/frontend#1509]

**Comment by maikReal** [comment]
@maxaleks Can you please describe the bug?

**Comment by maxaleks** [comment]
The `onConnect` callback is called twice [here](https://github.com/blockscout/frontend/blob/main/ui/address/contract/ContractConnectWallet.tsx#L32) and [here](https://github.com/blockscout/frontend/blob/main/ui/snippets/walletMenu/useWallet.tsx#L33)
