### ISSUE TITLE
contract interaction: nested tuple values are not parsed properly

### ISSUE THREAD

**Issue by tom2drum** [blockscout/frontend#1512]
### Description

When attempting to write to the contact method with a nested tuple, the value is not properly parsed before being passed to the `wagmi` library. Consequently, the user encounters an error.

![image](https://github.com/blockscout/frontend/assets/22130104/78ff3528-5e55-48f7-916d-3b5a3bbdad03)

### Link to the page

https://eth-sepolia.blockscout.com/address/0xc7F957c37193648D087E691016De9542273Be164?tab=contact_code

### Steps to reproduce

1. Go to https://eth-sepolia.blockscout.com/address/0xc7F957c37193648D087E691016De9542273Be164?tab=contact_code
2. Try to call method `updateFields` in the contract by passing "[1,2]" to nested tuple
3. See error

### App version

main branch (unrelease)

### Operating system

None

**Comment by jaymod** [comment]
Thanks for the quick fix @tom2drum! This is working great for us in the 1.23.0 build.
