### ISSUE TITLE
Gas Tracker page

### ISSUE THREAD

**Issue by tom2drum** [blockscout/frontend#1520]
temp link: https://www.notion.so/blockscout/Filecoin-Gas-tracker-0714004410734c55bcb976ac211225ee?pvs=4

**Comment by NikitaSavik** [comment]
@tgladilina to provide new popup design, incorporating both gwei and fiat price

**Comment by tom2drum** [comment]
The gas unit display can be controlled using the `NEXT_PUBLIC_GAS_TRACKER_UNITS` variable. It accepts an array with two possible values: "usd" and "gwei". The default value is `'["usd","gwei"]'`.

Here's how the app views behave based on the possible values of the environment (ENV) variable:

1. If the variable contains an array with two valid values:
   - If there is data for both units, values will be displayed in both units side by side where it is applicable.
   - If there is no data for the secondary unit, values in that unit will not be shown.
   - If there is no data for the primary unit but there is data for the secondary unit, values will be shown only in the secondary unit.
   - If there is no data for either the primary or secondary unit, "N/A" values will be shown for the primary unit and nothing will be shown for the secondary unit.

2. If the variable contains an array with one valid value:
   - Values will be shown only in that unit.
   - If there is no data for that unit, "N/A" values will be shown, even if there is data for the other unit.

3. If the variable is an empty array or contains only invalid values, the "Gas Tracker" feature will be disabled.
