### ISSUE TITLE
BENS multiprotocol support

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#1532]
Adjust icons for the Name Services
[Figma](https://www.figma.com/design/ErLH8qySSkpprB87H0onWw/Blockscout_Pages?node-id=13789-179402)
[What is new](https://www.notion.so/blockscout/BENS-v2-a9dc17a7929e462da95bcbec89556667#37d57a7097c74cd6a5ff7ba2e47881d5)

**What is new:**
We can now support multiple protocols on one chain, supporting the ccrosschain resolution

**General**:
- Whenever we show domain with the icon (lists and pages), this icon should now come from API

**Address page:**
- Reverse-resolved name and icon should now show popup on hover. This popup should contain metadata on the protocol
![Image](https://github.com/blockscout/frontend/assets/1701762/906472b8-dfa9-42b1-a5cb-ba144ba6fdd1)

**Search**:
- show every found domain as a separate row in the quick search
![Image](https://github.com/blockscout/frontend/assets/1701762/41358035-902c-47c8-9df5-a8e13b13da48)

**Lookup page**:
- add filter by Protocol
![Image](https://github.com/blockscout/frontend/assets/1701762/d3994d29-874c-4347-98dd-8699cf709a71)

**Comment by tgladilina** [comment]
Design in [Figma](https://www.figma.com/design/ErLH8qySSkpprB87H0onWw/Blockscout_Pages?node-id=13789-179402)
