### ISSUE TITLE
MetaSuites integration

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#1536]
Metadock is an open-source browser extension. 
We should researchthe possibility to make a PR with Blockscout support
https://github.com/blocksecteam/metadock

**Comment by NikitaSavik** [comment]
First priority features: 
1) Show tags
2) Show tx interpretation

**Comment by tom2drum** [comment]
Needs:
- list of features for v1
- list of chains/instances where extension should work

**Comment by NikitaSavik** [comment]
+ design for public tags/interpretation

**Comment by tom2drum** [comment]
components library which is used by MetaSuites - https://ant.design

**Comment by tgladilina** [comment]
[Design task](https://www.notion.so/blockscout/Design-For-MetaDock-extension-8be51b99eb1c4ae0a73f961ee086a073?pvs=4) 

![Image](https://github.com/blockscout/frontend/assets/103045386/0d5ab177-b11e-409d-88e2-dccafbf5d917)
![Image](https://github.com/blockscout/frontend/assets/103045386/f3e8accd-ba02-4f65-8520-051fa28fc3e7)

Tag 
![Image](https://github.com/blockscout/frontend/assets/103045386/77e5ad34-ae60-424c-9f35-700b357f0fa3)

**Comment by NikitaSavik** [comment]
Todo: Icons for chains

**Comment by tgladilina** [comment]
Icons for chains: 
![Base_160px](https://github.com/blockscout/frontend/assets/103045386/0479565e-dd03-4803-bb9b-373ed2fca6f9)
![Optimism_160px](https://github.com/blockscout/frontend/assets/103045386/fbdc7e71-d5d4-4317-99fa-a8754bcf48bb)
![Gnosis_160px](https://github.com/blockscout/frontend/assets/103045386/0e0ad83e-79cb-412e-801b-f5b8bca6c687)
![zkEvm_Polygon_160px](https://github.com/blockscout/frontend/assets/103045386/d3de98cc-4cc2-410a-9ae5-a253268e849b)
![Polygon_160px](https://github.com/blockscout/frontend/assets/103045386/402b6279-9beb-4b2e-bdd6-377fd70de33a)
![Ethereum_160px](

[Chains_logos.zip](https://github.com/blockscout/frontend/files/14522686/Chains_logos.zip)
https://github.com/blockscout/frontend/assets/103045386/2f0ca6db-ffb8-4b8c-a6ed-45d8db602b3e)

**Comment by tgladilina** [comment]
![zkEvm_Polygon_160px](https://github.com/blockscout/frontend/assets/103045386/aacb1574-efbb-4a61-86b0-caf5c7e4bfcd)
