### ISSUE TITLE
Swap button

### ISSUE THREAD

**Issue by maikReal** [blockscout/frontend#1539]
[PRODUCT TASK](https://www.notion.so/blockscout/Swap-button-e69a8122362b45a6a206a36c40bb9bd9?pvs=4)

## What do? 

Support the Swap button with additional analytical events on the header
Design: https://www.figma.com/file/4In0X8UADoZaTfZ34HaZ3K/Blockscout_2.0?type=design&node-id=15028:86613&mode=design&t=yUYgK1TBkc5Gh3SG-1

All detailed information inside the product task

**Comment by ulyanas** [comment]
@maxaleks @maikReal 
-Can the button be hidden via config?
- Button should be hidden by default in the version we distribute.

**Comment by maikReal** [comment]
@ulyanas By default the value of the env will be empty. It means the button will be hidden for all instances
