### ISSUE TITLE
Shibarium L1<>L2 views

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#1564]
For Shibarium, two table views to be added

**Deposits:**
- L1 block No
- L1 txn hash
- L2 txn hash
- User
- Age

**Withdrawals:**
- L2 block No
- L2 txn hash
- L1 txn hash
- User
- Age

**Api endpoints:**
[/api/v2/shibarium/deposits](https://puppyscan.shib.io/api/v2/shibarium/deposits)
[/api/v2/shibarium/deposits/count](https://puppyscan.shib.io/api/v2/shibarium/deposits/count)
[/api/v2/shibarium/withdrawals](https://puppyscan.shib.io/api/v2/shibarium/withdrawals)
[/api/v2/shibarium/withdrawals/count](https://puppyscan.shib.io/api/v2/shibarium/withdrawals/count)

Deployed on https://puppyscan.shib.io/
[Related backend PR](https://github.com/blockscout/blockscout/pull/8929)

**Comment by tom2drum** [comment]
wait for #1595
