### ISSUE TITLE
Missing checksum on address page and read contract page

### ISSUE THREAD

**Issue by GimluCom** [blockscout/frontend#1570]
### Description

In the read contract page, address values are displayed in a (lowercase) non-checksum version.
Accessing an address page using a lowercase address will display the address in the same format.

To increase user friendliness, addresses should be shown in their checksummed version.

### Link to the page

https://eth-sepolia.blockscout.com/address/0x16Fc5058F25648194471939df75CF27A2fdC48BC?tab=read_proxy#724c184c

### Steps to reproduce

1. Go to the read contract/read proxy page
https://eth-sepolia.blockscout.com/address/0x16Fc5058F25648194471939df75CF27A2fdC48BC?tab=read_proxy#724c184c
![image](https://github.com/blockscout/frontend/assets/79271880/f48e1cf0-29b9-42ad-a2c6-e184674a223b)

2. Clicking on the address will take you to its address page
https://eth-sepolia.blockscout.com/address/0xdee57160aafcf04c34c887b5962d0a69676d3c8b
![image](https://github.com/blockscout/frontend/assets/79271880/fa096c72-2f2f-4366-95ee-56389e826679)

In both places the checksummed version should be displayed instead ([0xDEe57160...](https://eth-sepolia.blockscout.com/address/0xDEe57160aAfCF04c34C887B5962D0a69676d3C8B))

### App version

v1.23.0-alpha.1

### Operating system

None

**Comment by tom2drum** [comment]
We display the address here in the same format as it comes in the API response. Should the fix be done on the back-end side then?

<img width="1677" alt="Screenshot 2024-02-05 at 8 22 10 AM" src="https://github.com/blockscout/frontend/assets/22130104/1b90deb8-c4cb-4774-bf11-2f795cab3c8b">

**Comment by GimluCom** [comment]
Imo the addresses in both examples could be checksummed in the frontend. I think the API is fine, but users interacting with the UI are likely to expect the copied address to be in the version that most applications use.

**Comment by GimluCom** [comment]
Yes, I think the API is fine the way it is now since the `address` type in Solidity is stored case-insensitive. However as a comparison, [etherscan](https://sepolia.etherscan.io/address/0x16Fc5058F25648194471939df75CF27A2fdC48BC#readProxyContract#F1) display the checksummed version in their interface, which I imagine most users prefer when using the read contract page.
