### ISSUE TITLE
OG description bug for NFT instances

### ISSUE THREAD

**Issue by yvaskov** [blockscout/frontend#1578]
## Description

Empty token name (?) in OG title, example:
https://eth.blockscout.com/token/0x7FF5601B0A434b52345c57A01A28d63f3E892aC0/instance/1967

![Image](https://github.com/blockscout/frontend/assets/72267126/d9878025-9e8f-4a0c-aa37-680e4b25a67f)

Can be reproduced on ERC-721 and ERC-1155 alike.

## Version

[v1.22.0](https://github.com/blockscout/frontend/tree/v1.22.0)

**Comment by NikitaSavik** [comment]
Title to be changed to"{Ethereum} NFT instance"
