### ISSUE TITLE
Logo alignment (mobile version)

### ISSUE THREAD

**Issue by tgladilina** [blockscout/frontend#1586]
**Issue**

Looks like a bug
![Image](https://github.com/blockscout/frontend/assets/103045386/f4129726-21e9-431b-ad9c-ff2ac86a442e)
![Image](https://github.com/blockscout/frontend/assets/103045386/950de936-aff4-4292-a341-6c4cb4a9c1f8)

**Solution:** 
Move logo to the left 
![Image](https://github.com/blockscout/frontend/assets/103045386/9ac72c5b-0338-44d0-baee-a19819556d56)

**Comment by tom2drum** [comment]
dublicate to #1555
