### ISSUE TITLE
Show social info for protocols

### ISSUE THREAD

**Issue by maikReal** [blockscout/frontend#1603]
[PRODUCT TASK](https://www.notion.so/blockscout/Social-info-about-the-project-b1f50c9377f748cba4490c830ae7110d?pvs=4)

## What to do? 

We need to add additional information inside the app. All details inside the product task

**Laucnh for all users with AB testing** 

Design: https://www.figma.com/file/4In0X8UADoZaTfZ34HaZ3K/Blockscout_2.0?type=design&node-id=18013%3A99991&mode=design&t=r4EZ6FjlF0tnoLR3-1

**Comment by maikReal** [comment]
@maxaleks I think you will get info from the marketplace DB (admin panel). That's why I created a task for the admin panel to support new **"Discord"** field in the database and changed the type format of **"github"** field from stroing to array

Here is the task: https://github.com/blockscout/blockscout-rs/issues/776

**Comment by maikReal** [comment]
@maxaleks Strange layouts when you open the mobile platform 
@tgladilina Can review this one as well. Seems we need to move buttons to the left side, near an arrow 





![Image](https://github.com/blockscout/frontend/assets/26190360/94281417-552f-4e18-817f-a12edcf63a79)

**Comment by tgladilina** [comment]
@maxaleks please move buttons to the left side

![Image](https://github.com/blockscout/frontend/assets/103045386/c01aa177-fd6d-4e0e-b39d-ebed39b64e2e)

**Comment by maikReal** [comment]
@maxaleks All looks good for now
