### ISSUE TITLE
Tests for the marketplace

### ISSUE THREAD

**Issue by maikReal** [blockscout/frontend#1605]
## What to do?

Need to cover the marketplace with basic frontend tests: the list of apps in the market + app page

**Comment by maikReal** [comment]
@tom2drum Can you pls describe the scope of this task?

**Comment by tom2drum** [comment]
> @tom2drum Can you pls describe the scope of this task?
🙄 write visual tests for components that are used on the marketplace page

also write tests for utility functions and hooks with complex logic
