### ISSUE TITLE
Apps with connected wallet work improperly on Shibarium

### ISSUE THREAD

**Issue by maikReal** [blockscout/frontend#1612]
## The problem

If I try to open apps with connceted wallet to Blockscout, some of them won't work improperly or won't be opened at all

## Steps to reproduce

1. Connect a wallet to Blockscout
2. Open the marketplace
3. Open any of apps. I found this behaviour with Marswap, Leetswap, WoofSwap 

## Examples

When I opened the Leetswap without a connected wallet 
![Image](https://github.com/blockscout/frontend/assets/26190360/c9ec212d-c905-495a-aecb-dafc7463ca0b)

When I opened Leetswap with connected wallet
![Image](https://github.com/blockscout/frontend/assets/26190360/155d6380-28c9-449d-bbbf-ca18025bee12)

Sometimes app doesnt' open at all

**Comment by maxaleks** [comment]
We were unable to reproduce the issue. If it's still relevant, please reopen the issue and provide more details. Thanks!
