### ISSUE TITLE
Support arrays of structs/tuples in contract method result

### ISSUE THREAD

**Issue by yvaskov** [blockscout/frontend#1655]
## Description

Currently we parse arrays of tuples incorrectly, example:

https://unreal.blockscout.com/address/0x747c6530dC1e2dfD19978955119da93703b1f746?tab=read_proxy
Method 5 `getAllPair`, args:
```
0x1111110000000000000000000000000000000000
6
0
```

![Image](https://github.com/blockscout/frontend/assets/72267126/a40ef768-ad3e-4d9d-95c6-7e23eb80d930)

Need to add support for this type of results. It would look like this:
```
*pair1 (tuple):
    version (uint8) : 1
    pair_address (address): 0x7bae255618b0e5783a81e2abc82219dd62bebb23,
    box_address (address): 0x9675c1a6ec968c2ab16ac7c04f9cad5a9c8d023a,
    ...
*pair2 (tuple):
    version (uint8) : 1
    pair_address (address): 0x6145dbad9b8afc226d66d29df35b9228c4763b67,
    box_address (address): 0xdb477e5dc1c36a168e324a086ae65c35bfd35052,
    ...
```

## Version
[v1.25.0](https://github.com/blockscout/frontend/tree/v1.25.0)

**Comment by tom2drum** [comment]
wait for https://github.com/blockscout/blockscout/issues/9558
