### ISSUE TITLE
Add AdButler as an additional ad provider

### ISSUE THREAD

**Issue by maikReal** [blockscout/frontend#1699]
**[PRODUCT TASK](https://www.notion.so/blockscout/AdButler-for-the-marketplace-apps-promo-7b7ebe55b86b45159b7f58054bc2de73?pvs=4)**

## What to do? 

We need to add AdButler as an additional option that will work alogn with some other ad providers. More details in the Product task

**Comment by isstuev** [comment]
https://www.adbutler.com/help/article/apps-events#response
