### ISSUE TITLE
frontend no data but the backend database has data

### ISSUE THREAD

**Issue by BlockgenStudio** [blockscout/frontend#1700]
### Description

i followed the manual deployment guidance and the backend is deployed successfully. i can see there is data in the tables.
how ever when i run the front end  by yarn dev, the front end shows no data

```

blockscout=# SELECT count(*) FROM transactions;
 count 
-------
 45734
(1 row)

blockscout=# SELECT count(*) FROM blocks;
  count  
---------
 1257422
(1 row)
```

![image](https://github.com/blockscout/frontend/assets/135279728/7c9c17c2-cb16-4630-8b14-d2b4763ab6d7)

here is my front end .env, NEXT_PUBLIC_API_PORT is 4000 since it's the default: https://docs.blockscout.com/for-developers/information-and-settings/env-variables
```
NEXT_PUBLIC_API_HOST=localhost
NEXT_PUBLIC_API_PORT=4000
NEXT_PUBLIC_API_PROTOCOL=http
NEXT_PUBLIC_STATS_API_HOST=http://localhost:8080
NEXT_PUBLIC_VISUALIZE_API_HOST=http://localhost:8081
NEXT_PUBLIC_APP_HOST=localhost
NEXT_PUBLIC_APP_PORT=3000
NEXT_PUBLIC_APP_INSTANCE=localhost
NEXT_PUBLIC_APP_ENV=development
NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL='ws'
```

i also tried to execute a backend API call, here is the output
```
curl http://localhost:4000/api/
{"message":"Params 'module' and 'action' are required parameters","result":null,"status":"0"}
```

how to fix this? Appreciate any input

### Link to the page

http://35.94.88.222:3000/

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### App version

v1.26.0-alpha

### Operating system

Linux

**Comment by isstuev** [comment]
Hi! the link you provided seems like not working
there's no api endpoint at /api/ path
try something like /api/v2/main-page/transactions or any other from the lib/api/resources.ts file
