### ISSUE TITLE
Add support of ERC-404 type

### ISSUE THREAD

**Issue by vbaranov** [blockscout/frontend#1725]
Backend implemented in https://github.com/blockscout/blockscout/pull/9407

Frontend should:
- allow to filter `ERC-404` type on the corresponding pages together with `ERC-20/721/1155`
- display 'ERC-404' category in the tokens dropdown

ERC-404 tokens list:
https://base.blockscout.com/api/v2/tokens?type=ERC-404

**Comment by isstuev** [comment]
waiting for backend bugfixes
https://github.com/blockscout/blockscout/issues/9699
https://github.com/blockscout/blockscout/issues/9697
