### ISSUE TITLE
Navigating to future block breaks further navigation

### ISSUE THREAD

**Issue by yvaskov** [blockscout/frontend#1745]
## Description

It is possible to navigate to future block from the Block details page, which results in 404 page. It's impossible to navigate back from this with browser controls.

![Image](https://github.com/blockscout/frontend/assets/72267126/d209f64f-75b7-4cd4-aaad-c23722b5a59e)

## Steps to reproduce

1. Open latest block details page
2. Press right by the block number - results in 404
3. Press Back on the browser controls

### Expected result

Previous page is displayed.

### Actual result

URL has changed to the previous page, but 404 is still displayed.

## Possible solution

We can forbid navigating past the latest block.

![Image](https://github.com/blockscout/frontend/assets/72267126/c395eddd-c9be-4016-aef7-7e10071b31df)

## Version

[v1.27.0](https://github.com/blockscout/frontend/tree/v1.27.0)

**Comment by NikitaSavik** [comment]
not relevant due to countdown appearance instead of 404
