### ISSUE TITLE
User Operations: add switcher to call data

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#1762]
[Design task](https://www.notion.so/blockscout/Design-For-calldata-switch-a83ed53af59249f791d47a71dd2777d8?pvs=4)
[Backend task](https://github.com/blockscout/blockscout/issues/9676)

**Comment by NikitaSavik** [comment]
@tgladilina please attach the URL to the design page

**Comment by tgladilina** [comment]
@NikitaSavik 

[Figma ](https://www.figma.com/file/4In0X8UADoZaTfZ34HaZ3K/Blockscout_2.0?type=design&node-id=2673-66208&mode=design&t=JNUaY32X7KTPpoSc-4)

Screen
<img width="1071" alt="Screenshot 2024-04-15 at 8 09 20 PM" src="https://github.com/blockscout/frontend/assets/103045386/9f2eb35d-17a6-40d3-96a8-13f31ff91941">

Tip for "Inner call data"
Inner call data is a predicted decoded call from this user operation

**Comment by tom2drum** [comment]
Examples:
https://base.blockscout.com/op/0x70541f98c9789972a5c61b6c6f9f630807a161cf254cf59feccab3580000ae0b
