### ISSUE TITLE
Adjust NFT token title

### ISSUE THREAD

**Issue by ulyanas** [blockscout/frontend#1790]
Implement new logic for showing NFT token title:
1) If NFT instance has Name, show it in the title 
For example, [here](https://eth.blockscout.com/token/0x7F59B64C6Ee521C0d7E590CF8e4B843cAa236F96/instance/512) title would be `CELL #512`
2) If there is no Name, show ID as it is now 
3) If the result title is long (for example [here](https://eth.blockscout.com/token/0x95987b0cdC7F65d989A30B3B7132a38388c548Eb/instance/57896044618658097711785492504343953926634992332820282019728792003956564819992)), truncate the number with adding (...) in the middle. If there is no number, truncate the entire string.  
Example: _Purse #578960...4819992_  

![Image](https://github.com/blockscout/frontend/assets/6618204/a01775a2-1acc-4220-9a58-e8bfc5fd2348)

**Comment by tom2drum** [comment]
Implementing middle-string truncation can be challenging. As we discussed previously, it's acceptable to truncate the title string at the end, following the pattern used by the Looksrare website.
