### ISSUE TITLE
Implementation name behind proxy name

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#1798]
[Design](https://www.notion.so/blockscout/Design-For-Contract-behind-proxy-name-12545f4bea7948a0b7c7c7b0c2257b78?pvs=4)

**Comment by NikitaSavik** [comment]
- Implementation has name: show implementation name (on click go to implementation)
- Otherwise show proxy name / hash
- 'copy' button should copy proxy address
- green 'link' icon should indicate that both implementation and proxy are verified

**Comment by tom2drum** [comment]
@tgladilina we need to adjust the tooltip mockup and showcase the case with multiple implementations. Each implementation has an address hash and an optional name. The actual number of implementations can be significant (e.g., 10 or even more).

<details><summary>Tooltip</summary>
<p>

![Image](https://github.com/blockscout/frontend/assets/22130104/243b08a0-33ae-43a2-b9b2-005d1630a743)

</p>
</details> 

[Example #1](https://eth.blockscout.com/address/0xc9e91eDeA9DC16604022e4E5b437Df9c64EdB05A?tab=write_proxy)

**Comment by tgladilina** [comment]
@NikitaSavik @tom2drum 
[mockup](https://www.figma.com/design/4In0X8UADoZaTfZ34HaZ3K/Blockscout_2.0?node-id=20543-278982&t=ou1SOxVZYNhS8ZDV-4) 
![Image](https://github.com/blockscout/frontend/assets/103045386/bea63212-b421-44d6-8589-288b3ea8bce7)
