### ISSUE TITLE
Add Ad banner to 404 page

### ISSUE THREAD

**Issue by isstuev** [blockscout/frontend#1799]

**Comment by tgladilina** [comment]
@ulyanas 
<img width="683" alt="Screenshot 2024-04-10 at 2 05 54 PM" src="https://github.com/blockscout/frontend/assets/103045386/981c29ce-d877-4281-9ef5-bfd4cc0b57cc">

or

<img width="685" alt="Screenshot 2024-04-10 at 2 06 13 PM" src="https://github.com/blockscout/frontend/assets/103045386/16dcb5a1-3903-4d5b-8565-144fd86288e8">

**Comment by tgladilina** [comment]
Mockup in [Figma](https://www.figma.com/file/4In0X8UADoZaTfZ34HaZ3K/Blockscout_2.0?type=design&node-id=5540-66612&mode=design&t=zxq4U7eNHq7IDNPK-4)

<img width="908" alt="Screenshot 2024-04-18 at 1 15 46 PM" src="https://github.com/blockscout/frontend/assets/103045386/d84f3c69-e25d-47bc-a9ca-0cb9836ff3d8">
