### ISSUE TITLE
custom 'claim funds' link for optimistic rollups

### ISSUE THREAD

**Issue by isstuev** [blockscout/frontend#1810]
https://explorer.zora.energy/tx/0xc8f54b89dec033b99c255ae69c363dd30ed57eb421ef580b82995478b390ba9c
need to add an env variable with current withdrawal link as a default

**Comment by tom2drum** [comment]
we've already had the variable `NEXT_PUBLIC_ROLLUP_L2_WITHDRAWAL_URL` but for some reason don't use it in the code 😓
