### ISSUE TITLE
Public tags: form re-design

### ISSUE THREAD

**Issue by tom2drum** [blockscout/frontend#1826]
Limitations and current implementation details:
- maximum addresses per form = 20
- maximum tags per form = 5
- no color picker available yet; users can set the background or text color by typing a valid color hex code without the "#" symbol
- "start over" buttons:
  - for a particular result page item - leads to a pre-filled form with requester information and addresses (without pre-filled tags)
  - from the overall submit result - leads to a pre-filled form with just requester information
- if user is authenticated, form will be pre-filled with info from their profile (nickname/name + email)

**Comment by tgladilina** [comment]
@tom2drum  @NikitaSavik  

**Design** 
https://www.figma.com/file/CEgxqWOzVulwfTUHhs0gUC/%F0%9F%94%A5-RESEARCH%2FDRAFTs?type=design&node-id=771-864&mode=design

**Comment by NikitaSavik** [comment]
@tgladilina please add recaptcha
+(i) tooltip text: Submit a public tag proposal for our moderation team to review

**Comment by tgladilina** [comment]
done

![Image](https://github.com/blockscout/frontend/assets/103045386/167475ce-358e-4e0c-aed7-c8d72aed7d03)
![Image](https://github.com/blockscout/frontend/assets/103045386/483320ec-12d8-46d9-8e00-aad05243d4fd)

**Comment by tom2drum** [comment]
Limitations and current implementation details:
- maximum addresses per form = 20
- maximum tags per form = 5
- no color picker available yet; users can set the background or text color by typing a valid color hex code without the "#" symbol
- "start over" buttons?
