### ISSUE TITLE
Contract method id tag and simulate write method call

### ISSUE THREAD

**Issue by tgladilina** [blockscout/frontend#1834]
**Now**
1 . [Transaction details](https://eth.blockscout.com/tx/0x46893ff99ef52c7cdac6abef631a4493b860005eff11733a8e05445cb12d26db?tab=logs)
![Image](https://github.com/blockscout/frontend/assets/103045386/b3e47d5b-a791-4204-b0f1-42baf25008cd)

2. [Contract details](https://eth.blockscout.com/address/0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad?tab=read_contract)
![Image](https://github.com/blockscout/frontend/assets/103045386/452be68f-a813-40a8-8851-5fed4b52d9e4)

**Updates**

- [ ]  1 . Transaction details - replace text with tag [FIGMA](https://www.figma.com/file/4In0X8UADoZaTfZ34HaZ3K/Blockscout_2.0?type=design&node-id=2673-66207&mode=design&t=RVHBoxBc7ECwkh4x-4)

![Image](https://github.com/blockscout/frontend/assets/103045386/de19f0bf-ff38-4f72-adfd-7e8e98916ce8)
![Image](https://github.com/blockscout/frontend/assets/103045386/4dbb23da-4416-4d40-9977-c67625d6118b)

- [ ] 2. Contract details - add method tag [FIGMA](https://www.figma.com/file/4In0X8UADoZaTfZ34HaZ3K/Blockscout_2.0?type=design&node-id=17762-101657&mode=design&t=4DgTThWeDbKO0zBu-4)

![Image](https://github.com/blockscout/frontend/assets/103045386/44289bc6-a35f-4748-aa08-a19054112c85)

**Comment by NikitaSavik** [comment]
+ for the write methods returning value: add '**simulate**' button to execute read action

**Comment by tom2drum** [comment]
If the blockchain interaction feature is not configured for the app, we will display the "Write methods" tab. However, we will disable the "Write" button for methods and provide a tooltip explaining why it is disabled.
