### ISSUE TITLE
'Certified' contracts

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#1860]
in the same fashion as we do for tokens:

![Image](https://github.com/blockscout/frontend/assets/1701762/fb6e65a3-03f4-40c1-914d-ebd8c2a77e44)

tooltip: _This contract has been certified by the chain developers_

add checkmark icon to:
- search results
- all transaction lists
- contract page
- verified contracts page

[Related backend task](https://github.com/orgs/blockscout/projects/8/views/1?filterQuery=contract&pane=issue&itemId=58515371)

**Comment by isstuev** [comment]
0xdC9D5762a7F3274753B91F087351ec25A3b9A5Ad
0x793EEdff1F64dFaE65E47bb310c1bd89d889eF94
