### ISSUE TITLE
NEXT_PUBLIC_ROLLUP_L2_WITHDRAWAL_URL mandatory

### ISSUE THREAD

**Issue by InoMurko** [blockscout/frontend#1865]
### Description

The code says it's mandatory:
```
    NEXT_PUBLIC_ROLLUP_L2_WITHDRAWAL_URL: yup
      .string()
      .when('NEXT_PUBLIC_ROLLUP_TYPE', {
        is: (value: string) => value === 'optimistic',
        then: (schema) => schema.test(urlTest).required(),
        otherwise: (schema) => schema.max(-1, 'NEXT_PUBLIC_ROLLUP_L2_WITHDRAWAL_URL cannot not be used if NEXT_PUBLIC_ROLLUP_TYPE is not defined'),
      }),
```

but docs don't:
https://github.com/blockscout/frontend/blob/main/docs/ENVS.md?plain=1#L392

### Link to the page

https://eth.blockscout.com

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### App version

1.2.0

### Operating system

None

**Comment by tom2drum** [comment]
Optimistic roll-ups require it, while it's optional for other roll-up types as per the validation schema. We can document this if needed.

**Comment by InoMurko** [comment]
Any reason why not make it consistent?

**Comment by tom2drum** [comment]
The Withdrawal URL is crucial for Optimistic rollups from our standpoint, but optional for other rollup types. Please correct me if I'm mistaken.

**Comment by InoMurko** [comment]
I guess it depends what was the argumentation? 

Regardless of their construction, I don’t see a reason why it would be mandatory from the explorers POV and optional for ZK. But as per first sentence, I lack your context. Anyway, tnx for exercising this (again, probably).

**Comment by tom2drum** [comment]
I'll discuss with the team to possibly standardize this across all rollups. For now, I'll update the docs to align with the validation schema. Thank you for your effort.
