### ISSUE TITLE
Public tags: dedicated tag page

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#1869]
[Design task](https://www.notion.so/blockscout/Design-For-Public-tag-singular-page-5364164abfef48778ced76943b59558b?pvs=4)
[Backend task](https://github.com/blockscout/blockscout/issues/9976)

**Comment by tgladilina** [comment]
@NikitaSavik  Need to discuss 
https://www.figma.com/file/CEgxqWOzVulwfTUHhs0gUC/%F0%9F%94%A5-RESEARCH%2FDRAFTs?type=design&node-id=1845-27461&mode=design&t=dWyLAmmKL7BDuVHt-4

**Comment by tgladilina** [comment]
@NikitaSavik let's discuss
https://www.figma.com/file/4In0X8UADoZaTfZ34HaZ3K/Blockscout_2.0?type=design&node-id=20792-47937&mode=design

**Comment by ulyanas** [comment]
Need API  for balance and Txn count @lok52

**Comment by tom2drum** [comment]
We need to change API response to match our common schema. It should have `items` and `next_page_paramas` fields instead of `addresses` and `nextPageParams`.

![Image](https://github.com/user-attachments/assets/63b33fa2-f28c-435e-b1ca-9944a4210f5b)
