### ISSUE TITLE
Unable to change front-end logo and bottom navigation

### ISSUE THREAD

**Issue by phpmac** [blockscout/frontend#1876]
### Description

Where is the modification location?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

1

### Backend version

1

### Elixir & Erlang/OTP versions

1

**Comment by tom2drum** [comment]
Description of all ENV variables you can find in ./docs/ENVS.md file

Example,
https://github.com/blockscout/frontend/blob/main/docs/ENVS.md#sidebar
https://github.com/blockscout/frontend/blob/main/docs/ENVS.md#footer
