### ISSUE TITLE
SEO: add canonicals and change meta titles

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#1888]
**1.For internal hrefs:**

- https://eth.blockscout.com/
- https://eth.blockscout.com/txs
- https://eth.blockscout.com/ops
- https://eth.blockscout.com/verified-contracts
- https://eth.blockscout.com/name-domains
- https://eth.blockscout.com/withdrawals
- https://eth.blockscout.com/tokens
- https://eth.blockscout.com/stats
- https://eth.blockscout.com/api-docs
- https://eth.blockscout.com/graphiql
- https://eth.blockscout.com/gas-tracker
- https://eth.blockscout.com/apps

Add 'canonical' parameter, e.g.
`<link rel="canonical" href="https://eth.blockscout.com/" />`

**2. Change metatag Title**

Page - 'Duplicate Meta Titles' (please ask @NikitaSavik for table URL)
- For root pages, change the title according to the table
- Change 'Ethereum' with chain name

**3. Change H1 Title**

Page - 'Duplicate H1 and Title'
- For root pages, change the H1 title according to the table (column \new h1\)
- Change 'Ethereum' with chain name

**Comment by NikitaSavik** [comment]
@maikReal - to provide schema for H2 for Dappscout pages, e.g. `Dappscout - {Category}`

**Comment by tom2drum** [comment]
Decided not to implement any changes on the Marketplace page.
All page titles (<h1>) will be changed only if variable `NEXT_PUBLIC_SEO_ENHANCED_DATA_ENABLED` is set to true
