### ISSUE TITLE
SolidityScan loader update

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#1893]
Instead of skeleton, show Solidity Scan logo animation while getting the scan results
animations: https://blockscout.slack.com/archives/D05JEU64SBS/p1715069964827939?thread_ts=1715069208.101399&cid=D05JEU64SBS
[Design task](https://www.notion.so/blockscout/Design-For-SolidityScan-loading-state-ef538b2df9f0490198b6ab773df0d562)

![Image](https://github.com/blockscout/frontend/assets/1701762/08da2955-1fff-4754-a3d4-e23059ed36d2)

**Comment by ulyanas** [comment]
Need animation

**Comment by tgladilina** [comment]
![Image](https://github.com/blockscout/frontend/assets/103045386/ec471272-98a9-4d56-a9ca-15378454cff9)

[figma components ](https://www.figma.com/file/4In0X8UADoZaTfZ34HaZ3K/Blockscout_2.0?type=design&node-id=19739-41324&mode=design&t=v8xxrZE6aNMsQk7b-4)
