### ISSUE TITLE
Blueprint contracts support

### ISSUE THREAD

**Issue by rimrakhimov** [blockscout/frontend#1907]
We need to add some notification window for blueprint contracts ([EIP-5202](https://eips.ethereum.org/EIPS/eip-5202))

For example:
https://etherscan.io/address/0x79D584d2D49eC8CE8Ea379d69364b700bd35874D#code

Whether the contract is blueprint will be returned from the `/api/v2/smart-contracts/0x...` endpoint as a `is_blueprint` field. Requires https://github.com/blockscout/blockscout/pull/10058 to be merged

**Comment by NikitaSavik** [comment]
Adding label to **contract tab**

**Comment by tgladilina** [comment]
@NikitaSavik 
![Image](https://github.com/blockscout/frontend/assets/103045386/bc2a0e03-86e2-4966-81aa-45ea0e52e6df)

![Image](https://github.com/blockscout/frontend/assets/103045386/561f58b8-c5e0-4d55-8247-040912f4d354)
![Image](https://github.com/blockscout/frontend/assets/103045386/936fd2aa-2792-4e00-ab55-76362c1128e0)

**Comment by tom2drum** [comment]
Examples:

https://eth.blockscout.com/address/0xDf41E21dAe8Bf6Ae3eddb83337f8364Eb7FC1659?tab=contract
https://eth-sepolia.k8s-dev.blockscout.com/address/0xF1B3efcfB131265233cD6Ae143e7b2B239c8690c?tab=contract
