### ISSUE TITLE
Token symbol logo

### ISSUE THREAD

**Issue by Neotericbit** [blockscout/frontend#1908]
### Description

I have tried to add a token symbol logo on a particular token deployed on a custom blockchain I did not find any administrative access from there so can you help me about add to the token logo?
![Screenshot from 2024-05-13 18-10-33](https://github.com/blockscout/frontend/assets/155805396/edb7d3c1-fca3-4e54-8de6-4ad5f37cffa6)

### Link to the page

https://testnet.poodl.org/tokens

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### App version

v1.29.2

### Browser

All browser

### Operating system

None

**Comment by tom2drum** [comment]
@Neotericbit, there is no way to add a logo to the token through the frontend app. The only option is to update a record in your Blockscout database.
