### ISSUE TITLE
3. Stats & charts: share option

### ISSUE THREAD

**Issue by tgladilina** [blockscout/frontend#1969]
**Share with link** 

![Image](https://github.com/blockscout/frontend/assets/103045386/89dd140f-4c8f-4749-9241-5881fa6ae584)

![Image](https://github.com/blockscout/frontend/assets/103045386/b1ceec92-03a9-424c-97a4-7df649ac8bce)

![Image](https://github.com/blockscout/frontend/assets/103045386/276a99ca-2da8-4bd1-8703-11c674c82168)

**Comment by NikitaSavik** [comment]
The same way twitter triggers system sharing, with "Share post via..." option, which should work great for mobile users
![image](https://github.com/blockscout/frontend/assets/1701762/387a1f9f-42a9-4987-9c28-dfb4df32c1e8)

**Comment by NikitaSavik** [comment]
Rename 'Zoom' label to 'Period'

**Comment by NikitaSavik** [comment]
+ add mixpanel event of type "Page widget" with the chart name as its info

**Comment by NikitaSavik** [comment]
Awaiting for `stats `microservice to finalize zoom-related modifications
