### ISSUE TITLE
Identicon render issue on `Name details` page on mobile

### ISSUE THREAD

**Issue by yvaskov** [blockscout/frontend#1970]
## Description

Identicons slightly cut on `Name details` pages (Safari mobile and Android Chrome)

### Examples

https://base.blockscout.com/name-domains/sam3bd2.base

![Image](https://github.com/blockscout/frontend/assets/72267126/5f813e37-c8d0-4351-9031-874675a2918a)
![Image](https://github.com/blockscout/frontend/assets/72267126/2c2866fc-f3dd-41ed-9e41-4dfc09843a79)

## Version

[v1.30.1](https://github.com/blockscout/frontend/tree/v1.30.1)

**Comment by tom2drum** [comment]
It seems to be a browser issue. I've checked the dimensions of the SVG element generated by the library, and they are correct.
