### ISSUE TITLE
Stats: Add data on the last 24hours

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#1975]

**Comment by bragov4ik** [comment]
From backend side ([PR](https://github.com/blockscout/blockscout-rs/pull/836#issue-2248507635)):
- approximate data (last data point) is marked with flag
- [.proto file diff](https://github.com/blockscout/blockscout-rs/pull/836/files#diff-3d1a1f2b53de0993e6bfde124928c687a406148576d252371b35b60f8e53e1a8R37)
- the feature is accessible in staging (https://eth-sepolia.k8s-dev.blockscout.com/stats)
- example of the retrieved flag:
```
❯ curl https://stats-sepolia.k8s-dev.blockscout.com/api/v1/lines/accountsGrowth\?from\=2024-06-05

{"chart":[{"date":"2024-06-05","value":"8647713"},{"date":"2024-06-06","value":"8666021","isApproximate":true}]}%
```
