### ISSUE TITLE
Call contract read methods from the client

### ISSUE THREAD

**Issue by tom2drum** [blockscout/frontend#2001]
**Dev:**
- Remove calls to API to the following resource: `/api/v2/smart-contracts/:hash/methods-read`, `/api/v2/smart-contracts/:hash/methods-read-proxy`, `/api/v2/smart-contracts/:hash/query-read-method`, `/api/v2/smart-contracts/:hash/methods-write`, `/api/v2/smart-contracts/:hash/methods-write-proxy`
- Get contract ABI from `/api/v2/smart-contracts/:hash` and display contract methods in the corresponding tabs; for proxy-contract also requests ABI if its implementation(s)
- [x] If there is no public RPC node for a blockchain, the client should make all requests via the Blockscout proxy node (need an example)

**Design:**
- [x] For methods that return a constant value show a "Retry" button when a query fails. Also, add a button to re-request the displayed value.
- [x] In the proxy tabs, we need a selector for contract implementations. This will allow users to choose methods from the desired contract.

**Testing:**
- [ ] Deploy a contract where we can test a major part of all corner cases (e.g with complex method arguments structure)

**Comment by tgladilina** [comment]
@tom2drum 
icon hover tip "Open contract details page in new tab"

![Image](https://github.com/blockscout/frontend/assets/103045386/bff0e45f-3ccc-42e3-b7f2-0990ff66c177)
