### ISSUE TITLE
Incorrect table header scroll on some pages

### ISSUE THREAD

**Issue by k1rill-fedoseev** [blockscout/frontend#2010]
Incorrect table header scroll on some pages.  

https://gnosis.blockscout.com/block/34405589?tab=txs

<img width="1728" alt="image" src="https://github.com/blockscout/frontend/assets/29590423/f6a45ae3-9ed2-4d5c-871b-fa5c567eaed6">

**Comment by isstuev** [comment]
fixed (for some pages) in https://github.com/blockscout/frontend/issues/2006
