### ISSUE TITLE
Support MUD framework

### ISSUE THREAD

**Issue by ulyanas** [blockscout/frontend#2020]
The goal is to integrate the MUD framework into Blockscout to enhance support for Redstone. 
MUD is a framework for building games on EVM chains. Each game is represented with a set of smart contracts and a storage called the Store. 

Key concepts:
Store - https://mud.dev/store/introduction 
World - https://mud.dev/world/introduction 

Store provides low-level primitives for storage. World provides the primitives for logic and access control on top of that storage. 

In the first iteration we aim to support views for Store tables, World contracts, and build corresponding APIs as a part of the Redstone support.  

Scope: 
- Show a list of all MUD Worlds contracts. For each MUD World user can either open a regular contract page or can view corresponding tables as a separate page
- Implement sorting and filtering for the tables 

Specs: https://www.notion.so/blockscout/Redstone-MUD-support-7412dab6b6a54b54ab6470dcc33e6bef?pvs=4
UI: https://www.figma.com/design/xrhhioK3lDXLjoteX1gBI5/Redstone-%26-MUD-support?node-id=1-8946
Overview: https://lattice.xyz/blog/introducing-redstone
Docs: https://mud.dev/introduction 

Notes: 
- Agreed to add a new ENV to turn on MUD integration 
- Agreed to implement MUD table of tables as a separate page

**Comment by isstuev** [comment]
https://explorer.garnetchain.com/api/v2/mud/worlds
