### ISSUE TITLE
WalletConnect does not work on firefox

### ISSUE THREAD

**Issue by JABirchall** [blockscout/frontend#2026]
### Description

Recent switch to use wallet connect and it fails to detect any wallets on the brower. 
It only functions for Chrome based browsers.

![](https://i.imgur.com/1vsrvy3.png)
![](https://i.imgur.com/QZgIxQd.png)

### Link to the page

https://explorer.hypra.network/

### Steps to reproduce

1. Go to explorer with Firefox
2. Click on Connect wallet
3. Observe no wallets detected

### App version

v1.31.1

### Browser

Firefox 126

### Operating system

Windows

### Additional information

Tested with Metamask and Frame

**Comment by tom2drum** [comment]
duplicate for #2059
