### ISSUE TITLE
Implement NFT instance metadata refetch button

### ISSUE THREAD

**Issue by vbaranov** [blockscout/frontend#2030]
API endpoint:
backend PR https://github.com/blockscout/blockscout/pull/10097
swagger update PR https://github.com/blockscout/blockscout-api-v2-swagger/pull/17

API endpoint is protected by reCAPTCHA (currently v2, similar to csv export endpoint protection)

The button should appear only, if a token instance already has the metadata.

This message appears on WS endpoint when metadata is re-fetched successfully:

```
{
   payload: {token_id: ^token_id, fetched_metadata: ^metadata},
   event: "fetched_token_instance_metadata",
   topic: token_instances:#{token_contract_address_hash_string}
 }
```

API endpoint is available to test at L1/L2 staging environments.

**Comment by NikitaSavik** [comment]
Please add this button to the 'more' section
![image](https://github.com/blockscout/frontend/assets/1701762/f3d84ee6-3fcf-459e-a605-aebcb7ea5c0f)
