### ISSUE TITLE
Fix dappscout-iframe issue with RainbowKit

### ISSUE THREAD

**Issue by maikReal** [blockscout/frontend#2033]
## What to do? 

- fix the issue with connection via RainbowKit
- fix sending transactions in SuperBridge app

For example: 
- https://optimism.blockscout.com/apps/superbridge

**Comment by maxaleks** [comment]
Related changes: https://github.com/blockscout/iframe/commit/d340c3940b4b311574eab5defc76a8a9a2344b50
