### ISSUE TITLE
ChainDoesNotSupportContract: Chain "Ethereum" does not support contract "ensUniversalResolver".

### ISSUE THREAD

**Issue by ayaoshu** [blockscout/frontend#2036]
### Description

ChainDoesNotSupportContract: Chain "Ethereum" does not support contract "ensUniversalResolver".  
NEXT_PUBLIC_NETWORK_RPC_URL=https://mainnet.infura.io/v3/

Why did this error occur
I tried to configure ensUniversalResolver in the currentChain and was able to skip this error;
Obviously, this is not the optimal solution,
What should I do

### Link to the page

/

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### App version

v1.31.1

### Operating system

None

**Comment by tom2drum** [comment]
Can you provide a full list of ENV variables? Do you use a public RPC URL for the chain? The one you provided doesn't seem to be in the list https://chainlist.org/
