### ISSUE TITLE
Block Countdown page

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#2068]
Separate page to show countdown timer

- Separate route for the page `block/countdown/{blocknum}`
- [API method example](https://eth.blockscout.com/api?module=block&action=getblockcountdown&blockno=21000000)
- If search is numbers-only and Blocks not found - show url to the countdown page 

[Design](https://www.notion.so/blockscout/3ce714e723c24c2e935932f3d186637e?v=c46a9c6d9ae24217b8f0f020ef408c1f&p=b3c80097a68942bea1ed777406c8573a&pm=c)

**Comment by tgladilina** [comment]
[Figma file](https://www.figma.com/design/ErLH8qySSkpprB87H0onWw/Blockscout_Pages?node-id=22391-276066&t=LRlc0EpUTMTWLIir-4) 

**Pages**

- [ ] blocks list (add link to Block Countdown page)
![Image](https://github.com/blockscout/frontend/assets/103045386/8cc384ab-3311-4673-88e7-85598732d5c0)

- [ ] Search page for Block Countdown 
![Image](https://github.com/blockscout/frontend/assets/103045386/67775315-477e-46b0-b7f9-5da1214e2ac2)

- [ ]  Block Countdown page 
![Image](https://github.com/blockscout/frontend/assets/103045386/35fd4764-254c-415d-b178-29df466253be)

- [ ]  Add option to the main search
![Image](https://github.com/blockscout/frontend/assets/103045386/13161f1a-e277-4e90-87fa-63cfa042b1a4)
