### ISSUE TITLE
Arbitrum support not working

### ISSUE THREAD

**Issue by InoMurko** [blockscout/frontend#2075]
### Description

Setting NEXT_PUBLIC_ROLLUP_TYPE: "arbitrum" 
prevents the startup of the application
```
🌀 Checking environment variables and their placeholders congruity...
👍 All good!

🌀 Validating ENV variables values...
🚨 ENVs validation failed with the following errors:
     NEXT_PUBLIC_ROLLUP_L2_WITHDRAWAL_URL cannot not be used if NEXT_PUBLIC_ROLLUP_TYPE is not defined
```

### Link to the page

asdf

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### App version

v1.32.0

### Operating system

None

**Comment by InoMurko** [comment]
If I set it to ```
NEXT_PUBLIC_ROLLUP_TYPE: "optimistic"
```
it works

**Comment by InoMurko** [comment]
```
/app $ env | grep NEXT_PUBLIC_ROLLUP_TYPE
NEXT_PUBLIC_ROLLUP_TYPE=arbitrum
```
and removing `NEXT_PUBLIC_ROLLUP_L2_WITHDRAWAL_URL` works.

so the combination of these two variables breaks the application
```
NEXT_PUBLIC_ROLLUP_L2_WITHDRAWAL_URL="whatever"
NEXT_PUBLIC_ROLLUP_TYPE=arbitrum
```

**Comment by InoMurko** [comment]
Actually, it says it is REQUIRED for optimistic rollup types, not that it is **forbidden**. Arbitrum support (or any other) should simply ignore this variable.

**Comment by isstuev** [comment]
I'm changing the error message, but we won't ignore unused variables, we're trying to keep a minimal variable list to minimize payload and prevent errors and misunderstandings
