### ISSUE TITLE
`View all results` button in search results opens a page from `check-redirect`

### ISSUE THREAD

**Issue by yvaskov** [blockscout/frontend#2077]
## Description

If `/api/v2/search/check-redirect` returns a result for the search query, `View all results` button redirects to that page instead of opening `Search results` page.

![Image](https://github.com/blockscout/frontend/assets/72267126/f9bb3386-29b6-4009-a763-4a2b1c325bda)

## Steps to reproduce

1. Open https://eth.blockscout.com/
2. Search for `123` or `vitalik.eth`
3. Click on `View all results`

## Version

[v1.32.0](https://github.com/blockscout/frontend/tree/v1.32.0)

**Comment by isstuev** [comment]
@NikitaSavik @ulyanas what would be the right scenario here?

"view all" links to the search results page, that has a redirect check. API returns redirect to the block page so we redirect user there. Pressing "enter" does the same. If we want for some reason to have different behavior for "enter" and "view all" we can implement some url param for example, but would it make sense? 

does it look ok for a user that we have redirect here? If I type "123" and see tokens in the first 10 results and press enter -- I will be redirected to the "123" block page.
