### ISSUE TITLE
Disable api.segment.io

### ISSUE THREAD

**Issue by klemenfn** [blockscout/frontend#2086]
### Description

I see a lot of these in the console:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.segment.io/v1/t. (Reason: CORS request did not succeed). Status code: (null).`

It seems to be an analytics collector but I can not figure out which module loads it and which config option, if any, turns this off or on.

### Link to the page

https://coston-explorer.flare.rocks/

### Steps to reproduce

1. Go to url
2. Open browser console
3. See cors errors for api.segment.io

### App version

v1.32.0

### Browser

Firefox

### Operating system

None

**Comment by tom2drum** [comment]
It is a part of "Email wallets" [feature](https://docs.walletconnect.com/appkit/flutter/core/options#enableemail) by WalletConnect
You can turn it off here - https://github.com/blockscout/frontend/blob/908bee2a6d5af94826e41cc51b9a455bd36c3224/lib/web3/wagmiConfig.ts#L38
