### ISSUE TITLE
Add new configurations for skins

### ISSUE THREAD

**Issue by tgladilina** [blockscout/frontend#2114]
- [ ] Change default fonts (for both H1/H2 and content) via two separate envs
![Image](https://github.com/user-attachments/assets/24460642-d99c-40f8-a9bb-2c7b71c2a9a2)

- [ ]  Add border for the main search section (inside;  dark/ light mode)

![Image](https://github.com/user-attachments/assets/9fadfe35-a1a9-4b48-8986-ce427fc230e4)
![Image](https://github.com/user-attachments/assets/36e78bb6-aa52-4dc0-8180-d9502b17a9bd)

- [ ] Change buttons color (main search section)

Solid CTA
- active #2B6CB0
- hover #4299E1
- color text

![Image](https://github.com/user-attachments/assets/c516d31f-53ed-446c-847c-47a72beb10d4)

- [ ] Change color for two types of buttons: (all pages; dark/ light mode) + color text 

__Solid CTA_
- active #2B6CB0
- hover #4299E1
- color text

CTA with blue border  
- active #2B6CB0
- hover #4299E1
- color text_

![Image](https://github.com/user-attachments/assets/e1449041-a7c8-4dd4-bb64-57b0242fd243)

**Comment by NikitaSavik** [comment]
Solid CTA & CTA with blue border are moved out of the task scope

**Comment by tom2drum** [comment]
**ENVs migration snippet**

current values
`NEXT_PUBLIC_HOMEPAGE_PLATE_BACKGROUND=<my-background>`
`NEXT_PUBLIC_HOMEPAGE_PLATE_TEXT_COLOR=<my-text-color>`

new values
`NEXT_PUBLIC_HOMEPAGE_HERO_BANNER_CONFIG={'background':['<my-background>'],'text_color':['<my-text-color>']}`
