### ISSUE TITLE
Main search vs search on page

### ISSUE THREAD

**Issue by tgladilina** [blockscout/frontend#2131]
**Problem:** 
different block's ID in the search field and on the block page after searching. 

![Image](https://github.com/user-attachments/assets/9519916f-01ce-45df-a84a-5eed63c216f3)

Video proof
https://github.com/user-attachments/assets/6c2f633a-c8c9-4b2d-b69b-1b245ec59dcb

**Comment by NikitaSavik** [comment]
Clear quick search field when the page is changed (route affected)
