### ISSUE TITLE
MUD bugs

### ISSUE THREAD

**Issue by tgladilina** [blockscout/frontend#2135]
**Table**

- [ ] Change grey color to black  

![Image](https://github.com/user-attachments/assets/26acb16d-b09f-4bd1-a3ea-f88c1751be27)

- [x] width of "Modified" column should be a fiх 
- [x] the content in the table should stretch across the entire width 

![Image](https://github.com/user-attachments/assets/90fccffe-2e49-4692-8785-4b6540c67185)

- [x] line and jump (attache video)
https://github.com/user-attachments/assets/4da69ed2-23bb-4039-a727-1d63afe7e190
![Image](https://github.com/user-attachments/assets/7fa157eb-69a1-4842-bd5e-929b18152a6c)

- [x] let's add the "copy"icon" to the first two columns ?
![Image](https://github.com/user-attachments/assets/2f11660a-5072-41b0-8b10-f3d2c7e7d08f)

**Comment by isstuev** [comment]
table header text color is used in all our tables, will move it's change to a separate task.
