### ISSUE TITLE
ens: add offchain support and fix bugs

### ISSUE THREAD

**Issue by sevenzing** [blockscout/frontend#2136]
need design: [task](https://www.notion.so/blockscout/Import-DNS-names-into-the-ENS-protocol-c33bde0a9a2d4f5bab210948c51bc95b)

1. add warning to detailed domain view if domain is stored offchain [[docs](https://eips.ethereum.org/EIPS/eip-3668)] (flag `stored_offchain`)
2. add note if domain is resolved using wildcard techique [[docs](https://docs.ens.domains/ensip/10)] (flag `resolved_with_wildcard`)
3. add field `resolver` to detailed view
4. now field `owner` can be null. I guess this is the reason why ens button is hidden here:
https://eth.blockscout.com/address/0xD578780f1dA7404d9CC0eEbC9D684c140CC4b638
![Image](https://github.com/user-attachments/assets/3a7269cf-e00d-4678-9825-95acdcbb49ef)

| offchain | wildcard | text                                                                                        |
| -------- | -------- | ------------------------------------------------------------------------------------------------- |
| true     | true     | `The domain name is resolved offchain using EIP-3668: CCIP Read & EIP-2544: Wildcard Resolution.` |
| false    | true     | `The domain name is resolved using EIP-2544: Wildcard Resolution.`                                |
| true     | false    | `The domain name is resolved offchain using EIP-3668: CCIP Read.`                                 |

EIP-3668: CCIP Read —  https://eips.ethereum.org/EIPS/eip-3668
EIP-2544: Wildcard Resolution. —  https://eips.ethereum.org/EIPS/eip-2544

Resolver tooltip:
The resolver contract provides information about a domain name

Design  - [FIGMA](https://www.figma.com/design/ErLH8qySSkpprB87H0onWw/Blockscout_Pages?node-id=13828-48043&t=n0zlLFQr4SOHsYci-4)

<img width="749" alt="Screenshot 2024-08-02 at 8 00 02 PM" src="https://github.com/user-attachments/assets/8155db7b-6165-40d0-8b85-0ef63d79e606">

**Comment by tom2drum** [comment]
Example on staging - https://eth-sepolia.k8s-dev.blockscout.com/name-domains/%F0%9F%92%8E.gmcafe.eth

Examples on prod - https://github.com/blockscout/blockscout-rs/issues/937#issuecomment-2252474866
