### ISSUE TITLE
Share a link button for Dappscout

### ISSUE THREAD

**Issue by maikReal** [blockscout/frontend#2141]
## What to do?

We need to add a share icon that will generate a share link for a user, so, he can share it on social media
More details in [the product task](https://www.notion.so/blockscout/Share-a-dapp-for-Dappscout-8a38e2da19c947359d0dc9a84279c7ae?pvs=4)

**Comment by tgladilina** [comment]
![Image](https://github.com/user-attachments/assets/9b6b9fbb-6e0b-4562-bed4-effc45172be1)
![Image](https://github.com/user-attachments/assets/3458c8d9-a986-4827-82fa-6e496bc178a1)

@maikReal @maxaleks we need change  text "copy to clickboard" to "copy  link to share"  Makes sense?

example for a stats page we've applied :
![Image](https://github.com/user-attachments/assets/aa18529a-0fff-4c7c-afcc-2af5e54b782e)

**Comment by maikReal** [comment]
The task is already deployed on prod. Seems it's a duplicate
