### ISSUE TITLE
Two CSP issues

### ISSUE THREAD

**Issue by klemenfn** [blockscout/frontend#2213]
### Description

Two CSP issues are logged on v1.33.2. I can't see anything not working so seems minor. Second one appears to be in the styles.

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' *.coston-explorer.flare.network coston-explorer.flare.network 'sha256-e7MRMmTzLsLQvIy1iizO1lXf7VWYoQ6ysj5fuUzvRwE=' coinzillatag.com servedbyadbutler.com 'sha256-wMOeDjJaOTjCfNjluteV+tSqHW547T89sgxd8W6tQJM=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=' *.slise.xyz https://api.hypelab.com d1q98dzwj6s2rb.cloudfront.net static.cloudflareinsights.com https://www.google.com/recaptcha/api.js https://www.gstatic.com https://translate.google.com 'sha256-FDyPg8CqqIpPAfGVKx1YeKduyLs0ghNYWII21wL+7HM=' blob: https://cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/loader.js https://cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/editor/editor.main.js https://cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/editor/editor.main.nls.js https://cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/basic-languages/solidity/solidity.js https://cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/basic-languages/elixir/elixir.js https://cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/base/worker/workerMain.js". Either the 'unsafe-inline' keyword, a hash ('sha256-9A7qFFHmxdWjZMQmfzYD2XWaNHLu1ZmQB0Ds4Go764k='), or a nonce ('nonce-...') is required to enable inline execution.

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' *.coston-explorer.flare.network coston-explorer.flare.network 'sha256-e7MRMmTzLsLQvIy1iizO1lXf7VWYoQ6ysj5fuUzvRwE=' coinzillatag.com servedbyadbutler.com 'sha256-wMOeDjJaOTjCfNjluteV+tSqHW547T89sgxd8W6tQJM=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=' *.slise.xyz https://api.hypelab.com d1q98dzwj6s2rb.cloudfront.net static.cloudflareinsights.com https://www.google.com/recaptcha/api.js https://www.gstatic.com https://translate.google.com 'sha256-FDyPg8CqqIpPAfGVKx1YeKduyLs0ghNYWII21wL+7HM=' blob: https://cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/loader.js https://cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/editor/editor.main.js https://cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/editor/editor.main.nls.js https://cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/basic-languages/solidity/solidity.js https://cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/basic-languages/elixir/elixir.js https://cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/base/worker/workerMain.js". Either the 'unsafe-inline' keyword, a hash ('sha256-kS8ku4A+xc/bRW02WdkQ7gbUVSH5y5LbV4UAM3yoSro='), or a nonce ('nonce-...') is required to enable inline execution.

### Link to the page

https://coston-explorer.flare.network

### Steps to reproduce

1. Go to https://coston-explorer.flare.network/
2. Open console
3. Two CSP errors are logged

### App version

v1.33.2

### Operating system

None

**Comment by tom2drum** [comment]
It was related to the color mode script from ChakraUI since you've set the default value to "dark/dim". I have pushed the fix to the main branch.
Thanks for reporting! 🙌
