### ISSUE TITLE
Display checksum-ed addresses

### ISSUE THREAD

**Issue by k1rill-fedoseev** [blockscout/frontend#2222]
The following links should lead to the same result, address in the page header should be automatically checksummed, copy to clipboard button should also always copy checksummed address:
- https://eth.blockscout.com/address/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
- https://eth.blockscout.com/address/0xa0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48

**Comment by tom2drum** [comment]
Also show the same hash in the QR-code modal

<img width="627" alt="image" src="https://github.com/user-attachments/assets/fab9aa27-2993-4da6-bbc1-ade071747685">
