### ISSUE TITLE
Blackfort: validators page

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#2233]
[Testnet API handle](https://blackfort-testnet.blockscout.com/api/v2/validators/blackfort)
Similiar to [validator page](https://stability.blockscout.com/validators) for Stability we need to create one for Blackfort
https://github.com/blockscout/blockscout/issues/10008
Table should show these fields:

- Address
- Name
- Comission
- Self bonded
- Delegate amount

**Comment by isstuev** [comment]
sorts: address_hash and blocks_validated

**Comment by theiceeman** [comment]
Hello, @NikitaSavik 
Does every chain need to implement their own custom implementation of the validators page?
Im trying to enable the page for our chain currently, and just enabling the env below does nothing.
Thanks.
NEXT_PUBLIC_WEB3_DISABLE_ADD_TOKEN_TO_WALLET

**Comment by NikitaSavik** [comment]
Hello @theiceeman,
For the moment - yes, validator pages are based on external API
Generic validator information is something we have on the roadmap, but this task has no ETA for now

**Comment by theiceeman** [comment]
Alright, Nikita
We've proceeded to do this.
Thank you
