### ISSUE TITLE
Wrong currency symbol on stats page

### ISSUE THREAD

**Issue by klemenfn** [blockscout/frontend#2250]
### Description

Stats page shows ETH as currency instead of, presumably, `NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL`.

### Link to the page

https://coston-explorer.flare.network/stats

### Steps to reproduce

1. Go to https://coston-explorer.flare.network/stats
2. Currency symbol is ETH instead of CFLR.

### App version

v1.33.2

### Operating system

None

**Comment by tom2drum** [comment]
Coin symbol for the graphs on stats page can be configured in the stats micro-service itself. I believe `STATS_CHARTS__TEMPLATE_VALUES__NATIVE_COIN_SYMBOL` variable is responsible for that.
