### ISSUE TITLE
New quick-action buttons and improvements on read/write tabs

### ISSUE THREAD

**Issue by k1rill-fedoseev** [blockscout/frontend#2251]
Similar to the existing buttons for quick integer input:

![Image](https://github.com/user-attachments/assets/0d9d759c-d317-4bad-a37e-7d0c03bba4f0)

it's suggested to also add the following:

1. "SELF" (or "ME", or "WALLET", etc..) button for fields of type address, which inputs the address of the collected wallet, if any.
2. "MAX" button for fields of type int*, uint*, which inputs the max allowed value for the given type (e.g. 2**256 - 1 for uint256, 2**31 - 1 for int32)
3. "NOW+1h" button for fields of type int*, uint*, whose field name match the following regex: `/.*timestamp|deadline|expiration|expiry.*/i`. "MAX" button should be hidden for such fields.
4. There should be a button to copy the constructed calldata to the clipboard, near write/read/simulate buttons. Button should only appear/activate when all the fields are filled and validated.
5. Input fields should have the `data-1p-ignore` attribute specified to disable 1password widget. Currently it's incorrectly displayed on fields of type address

**Comment by tgladilina** [comment]
Done 

<img width="1077" alt="Screenshot 2024-10-07 at 2 51 20 PM" src="https://github.com/user-attachments/assets/0e13e6b7-696e-46c1-a209-980d1c2a03d8">

**Comment by tom2drum** [comment]
Examples of contract methods with time-related arguments

https://eth.blockscout.com/address/0x891a93698d083a5fd220D8Cbac6d6fb1E6ffc88f?tab=write_contract#f3995c67

https://eth-sepolia.k8s-dev.blockscout.com/address/0x0bFca4919378394344533130e84914c00f9E7Aa1?tab=write_contract#414bf389
