### ISSUE TITLE
New way of adding custom ABIs

### ISSUE THREAD

**Issue by k1rill-fedoseev** [blockscout/frontend#2252]
Suggestion is to add a modal for adding/modifying custom ABIs of contracts on the contract tab. Button triggering the modal can be placed to the right of the 

![Image](https://github.com/user-attachments/assets/0560afbf-e214-4075-bf0c-14fac02e77fa)

It'll allow user to add/change custom ABI without leaving a tab, opening a new one, manually copying the contract address, etc.

**Comment by tgladilina** [comment]
[Mockup](https://www.figma.com/design/ErLH8qySSkpprB87H0onWw/Blockscout_Pages?node-id=24242-34834&t=ninCPH5kGol1W3JC-4) 
![Image](https://github.com/user-attachments/assets/41ba26a4-80eb-43ff-beed-9bd859da8154)

**Comment by tgladilina** [comment]
https://www.figma.com/design/ErLH8qySSkpprB87H0onWw/Blockscout_Pages?node-id=24244-39118&t=tD7SHsaPgawwPUW7-4

<img width="1026" alt="Screenshot 2024-10-18 at 6 58 25 PM" src="https://github.com/user-attachments/assets/a3abb185-6ec3-4bcf-8523-d43c82cc66d0">
