### ISSUE TITLE
Token transfers list page

### ISSUE THREAD

**Issue by vbaranov** [blockscout/frontend#2257]
Backend [task](https://github.com/blockscout/blockscout/issues/10717) / [implementation](https://github.com/blockscout/blockscout/pull/10801)
API endpoint: https://eth-sepolia.k8s-dev.blockscout.com/api/v2/token-transfers

Keyset pagination with [block_number, index] is supported.
Filtering by token type (`type` query parameter with available values ERC-20/ERC-721/ERC-1155/ERC-404) is supported.
Search, CSV download are not supported in the current implementation.

**Comment by NikitaSavik** [comment]
Icon - https://www.notion.so/blockscout/Design-For-token-transfers-icon-af5eca156182430984e3ce0375e24d93?pvs=4
