### ISSUE TITLE
Add new sorting option to Dappscout

### ISSUE THREAD

**Issue by maikReal** [blockscout/frontend#2260]
[**PRODUCT TASK**](https://www.notion.so/blockscout/Sorting-by-the-number-of-rates-1073d73641f88075909adf4cc7e93b45?pvs=4)

## What to do?

Add a new sorting option. All details in the product task

**Comment by IamLRBA** [comment]
Hello @maikReal , May i please be assigned this issue.
Thanks!

**Comment by tom2drum** [comment]
Hi @IamLRBA. Sorry for late reply. Sure, you can try to do this issue.
