### ISSUE TITLE
Celo: Epoch rewards tab on Address view

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#2261]

**Comment by tgladilina** [comment]
@fedor-ivn 

[page in Figma](https://www.figma.com/design/idSaO1QSqW9FXsLiwPybJx/API-for-celo-epoch-rewards-and-fees-breakdown?node-id=314-13789&t=DVvRavqSb9XN00jx-4)

![Image](https://github.com/user-attachments/assets/6c8771f4-772b-41b0-b7d5-584be8dd5422)
![Image](https://github.com/user-attachments/assets/f4effbaa-ecad-4157-8ef6-490893876387)

Need copy for tooltips

**Comment by fedor-ivn** [comment]
Implement Epoch rewards tab on the Address view page.


## Background

This tab deals with election rewards associated with the address of interest. When the user opens the Epoch rewards tab, it should display the paginated table containing info about:

1. Epoch block, in which the address was rewarded.
2. Address of an account, which is associated with the reward.
3. Amount of the reward and the currency in which the reward is paid.

## API

The data is obtained through `/api/v2/addresses/{address_hash}/election-rewards` endpoint which returns the paginated list of rewards.

Example: https://celo-alfajores.blockscout.com/api/v2/addresses/0xAe1ec841923811219b98ACeB1db297AADE2F46F3/election-rewards

## UI customisations

[Page in Figma](https://www.figma.com/design/idSaO1QSqW9FXsLiwPybJx/API-for-celo-epoch-rewards-and-fees-breakdown?node-id=314-13789&t=DVvRavqSb9XN00jx-4).

Note that tags under `Reward type` should have different tooltips:

| Reward type         | Tooltip |
| ------------------- | ------- |
| `group`             | WIP     |
| `validator`         | WIP     |
| `delegated-payment` | WIP     |
| `voter`             | WIP     |
