### ISSUE TITLE
Search shortcut

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#2265]
Create a keyboard shortcut to put search field on focus.
On '/' keydown - set focus to quick search field (if present)
[Original proposal](https://blockscout.canny.io/admin/feedback/feature-requests/p/make-pressing-the-key-bring-focus-to-the-search-bar?boards=feature-requests)

**Comment by tgladilina** [comment]
Component  in [Figma ](https://www.figma.com/design/4In0X8UADoZaTfZ34HaZ3K/BS_2.0-Components?node-id=1024-25555&t=aBP3lIGuhC7VbV1m-4)
<img width="543" alt="Screenshot 2024-10-14 at 9 53 35 PM" src="https://github.com/user-attachments/assets/46c9c26f-61f4-4711-8a27-8e62c3f0605c">
