### ISSUE TITLE
Homepage for rollups: block<>batch switcher

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#2292]
For the rollups, we need to add new ENV, which will switch this block on the main page:
![Image](https://github.com/user-attachments/assets/3e030f84-a90e-4f89-a237-68002a2808ef)
Depending on the config, we should be able to switch between batches and blocks

**Comment by tom2drum** [comment]
ENV value: `NEXT_PUBLIC_ROLLUP_HOMEPAGE_SHOW_LATEST_BLOCKS=true`
