### ISSUE TITLE
"Need gas?" link is dead

### ISSUE THREAD

**Issue by skyminelabs** [blockscout/frontend#2301]
### Description

On https://gnosis.blockscout.com/

The "Need gas?" link is dead

Goes to here but dead: https://gnosis.blockscout.com/apps/smol-refuel

### Link to the page

https://gnosis.blockscout.com/apps/smol-refuel

### Steps to reproduce

1. Go to https://gnosis.blockscout.com/
2. Click on "Need gas?" 
3. Get to https://gnosis.blockscout.com/apps/smol-refuel
4. See Dead

### App version

current

### Operating system

None

**Comment by tom2drum** [comment]
Fixed
