### ISSUE TITLE
Integrate easter egg games

### ISSUE THREAD

**Issue by maikReal** [blockscout/frontend#2315]
## What to do?

We need to integrate games that we created during our hackathon: 
- 8x8 game: https://review-games.k8s-dev.blockscout.com/
- CapyRun: https://review-games.k8s-dev.blockscout.com/block/countdown/1000000000000

### CapyRun game
We need to make some changes there:
1. Add a score that will be changing while a user plays
2. Add a small message for a user that he needs to achieve X score to get some prize
3. Show a mint button when a user reaches X score. We can stop the game, or make it infinite 
4. A user shouldn't easily achieve X score, so, we need to make a game a bit complicated 

### 8x8 game
Also, need to make some changes as well:
1. Show a mint button when a user can solve a puzzle 
2. Need to come up with a mechanic how to avoid link sharing to the mint page with other users

P.S. We need to add a user to whitelist if he won a game. In this case, he needs to connect a wallet and sign a message. If he does this, he will be added to gthe whitelist 
Contact @maikReal reagarding the whitelist

**Comment by ulyanas** [comment]
@maikReal  ToDo: clarify regarding the whitelist

**Comment by isstuev** [comment]
I fixed the capyrunner game and added score of 1000. Waiting for the image and other details.

**Comment by maikReal** [comment]
@isstuev Regarding the capy runner badge:

the algorithm should be the following:
1. When a user reaches 1000 we can tell him that he can mint an epic hidden badge 
2.  There will be a title about this and an action button
    - Title: You unlocked a hidden badge!
    - Subtitle: Congratulations! You’re eligible to claim an epic hidden badge!
    - Action button: Claim now
3. When a user clicks on a button, we'll redirect him to the following page: https://badges.blockscout.com/mint/hiddenBlockBadge (it's not available right now, I'll enable it later)


I think we don't need to show a badge image in Blockscout, text should be enough
