### ISSUE TITLE
Interpretation stub for failed txs

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/frontend#2322]
![Image](https://github.com/user-attachments/assets/e9b2d365-3d8c-4c7c-85ea-dacf01148663)
[Example](https://base.blockscout.com/tx/0x30ff36b5cfb6d0a41fc756301146667397e491864a90e32da662a458655454fa?tab=index)
For failed transactions, lets show 
`address `**failed** to call `method `on `addr`

**Comment by IamLRBA** [comment]
Hello @NikitaSavik , may i please be assigned this issue.
Thanks!

**Comment by NikitaSavik** [comment]
Hey @IamLRBA thank for you willingness to contribute to Blockscout!
