### ISSUE TITLE
ETH - SEO Tweaks for Gas Tracker Page

### ISSUE THREAD

**Issue by maikReal** [blockscout/frontend#2340]
We are experimenting with a new initiative by tweaking pages to help rank them better on Google. The following suggestions are recommended to be added to FE for Gas Tracker Page in order to get a higher listing based on rich text and optimizations. We will attempt this for ETH instance and if it works well we can proceed with others.  For full research on this please take a look at this [notion page](https://www.notion.so/blockscout/SEO-Rich-Texts-Keywords-1273d73641f88034af50c348ad1516a7?pvs=4)

### Blockscout suggested additions for “ETH Gas”

- **H1 Suggestion: Ethereum Gas  < Value of current avg gas in GWEI>**

- **H2 Suggestion: Track Ethereum Gas Fees <Current gas in GWEI>**

- **SEO Suggestions**
    - ETH gas fees tracker
    - Ethereum gas fee explorer
    - Real-time gas fee estimates
    - Ethereum gas fees Blockscout
**** Any of these can be added

- **FAQ Addition**
    - “What does Gas refer to on the Blockchain”
        - Gas is the amount of native tokens required to perform a transaction on the blockchain.
    - "How can I check Ethereum gas fees using Blockscout?"
        - You can easily check live Ethereum gas fees on Blockscout by visiting our gas tracker. It displays current gas fees in Gwei for all Ethereum transactions.
    - "What is the average gas fee for Ethereum transactions?"
        - The average gas fee for Ethereum transactions depends on network congestion and transaction complexity. Blockscout provides real-time gas fee estimations to help users make informed decisions.
    - "How does Blockscout calculate gas fees?"
        - Blockscout calculates Gas fees based on the average price of gas fees spent for the last 200 blocks

- **Snippet:** "Real-Time Ethereum Gas Fee Tracker | Blockscout” or "Track Ethereum Gas Fees in Gwei | Blockscout Explorer”
***What we want to see in google search result under H1 title

- **Other Optimizations:**
    - Meta Descriptions: "Explore real-time Ethereum gas fees with Blockscout's advanced gas fee tracker. Get accurate Gwei estimates and track transaction costs live.”
    - Enhanced Snippets:  "Track Ethereum gas fees live on Blockscout. Get real-time Gwei estimates for fast, average, and slow transactions, and explore gas fees across the Ethereum blockchain.”
**** What we want to see in google snippets
    -[ AMP formatting](https://www.semrush.com/blog/amp-pages/)

**Comment by isstuev** [comment]
I'm just going to leave this here
![Image](https://github.com/user-attachments/assets/700902a9-cb61-4f92-b700-235e694415e8)

**Comment by isstuev** [comment]
I also disagree with adding current gas price to the H1. A static H1 is generally better for SEO, as constantly changing headers can hinder indexing and ranking consistency.

**Comment by isstuev** [comment]
I don't quite get what to do with 'SEO suggestions' and 'Enhanced snippets' part, it's not like we can just put an invisible text somewhere and make it work. Also I didn't find an 'enhanced snippet' definition, there is a 'featured snippet' and there is no specific way to make our snippet 'featured'
![Image](https://github.com/user-attachments/assets/85ee22f3-60cc-4703-ad6a-2a905b195fa0)

**Comment by isstuev** [comment]
Also I found out that it's not recommended to use brands in the FAQ (if it's for SEO purposes) 
Because the idea is to provide answers to the popular questions, and a question 'How can I check Ethereum gas fees using Blockscout' is _probably_ less popular than 'How can I check Ethereum gas fees'

**Comment by maikReal** [comment]
@TheD0SH Can you pls check the comments above?

**Comment by TheD0SH** [comment]
> I'm just going to leave this here ![Image](https://private-user-images.githubusercontent.com/108066576/381720140-700902a9-cb61-4f92-b700-235e694415e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzOTMxMzEsIm5iZiI6MTczMDM5MjgzMSwicGF0aCI6Ii8xMDgwNjY1NzYvMzgxNzIwMTQwLTcwMDkwMmE5LWNiNjEtNGY5Mi1iNzAwLTIzNWU2OTQ0MTVlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxNjQwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGYyZDc2ZTU4ZWY4MzVkN2Y5YTAyYzZmNzQ1OTg1OWVkODkzMzEwOWZmYjc3MTQwNDgwYjU0YWI0NjBlOGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LwCiW8nziWTxfsb37bxe7Yz7nk6dj-opCCid_5mNEfM)

Yes i saw this as well but its still being utilized within the [rich-text check](https://search.google.com/test/rich-results), why show this if its not being used?  Up to you really if we want to proceed here 



> I also disagree with adding current gas price to the H1. A static H1 is generally better for SEO, as constantly changing headers can hinder indexing and ranking consistency.

number 1 result is ES, they have it right within the H1, 2nd result Blocknative same here. What suggestion do you have here that could help us rank? 
![image](https://github.com/user-attachments/assets/81cdc3ea-ce17-44fd-bab3-5cd5d2f977f5)


> I don't quite get what to do with 'SEO suggestions' and 'Enhanced snippets' part, it's not like we can just put an invisible text somewhere and make it work. Also I didn't find an 'enhanced snippet' definition, there is a 'featured snippet' and there is no specific way to make our snippet 'featured' ![Image](https://private-user-images.githubusercontent.com/108066576/381732065-85ee22f3-60cc-4703-ad6a-2a905b195fa0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzOTMxMzEsIm5iZiI6MTczMDM5MjgzMSwicGF0aCI6Ii8xMDgwNjY1NzYvMzgxNzMyMDY1LTg1ZWUyMmYzLTYwY2MtNDcwMy1hZDZhLTJhOTA1YjE5NWZhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxNjQwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjA5ZTI2MDAyNjU4YjZmYzVkMjk4YmY4NGI0ODA4ODFhZTQ1ODY1OWYyZGZjYzYyZDkxOWQ4ZTYyMmFiODExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Syhl-BQWipKDCf54Ul3xfElMZwTPoD6XRKvltFpypHw)

The idea behind the featured/enhanced snippet is to create a subtitle under H1 or some relative text that can include those words. I know it hinders the UX but maybe something along these lines could work wyt? 
![image](https://github.com/user-attachments/assets/ee7a7122-650d-4e76-8cd7-2e3c3e573a85)


> Also I found out that it's not recommended to use brands in the FAQ (if it's for SEO purposes) Because the idea is to provide answers to the popular questions, and a question 'How can I check Ethereum gas fees using Blockscout' is _probably_ less popular than 'How can I check Ethereum gas fees'

Feel free to tweak the text as you see fit, after all this is a test to see if we can produce any results on our ranking.

**Comment by isstuev** [comment]
>Yes i saw this as well but its still being utilized within the [rich-text check](https://search.google.com/test/rich-results), why show this if its not being used?

I don't see any connection in their docs between reach text and AMP, they are separate parts of the doc.
In general, AMP is a lighter version of a website, like one more web app. It shows less content, uses less JS, etc (that's not for our case). And it's a separate app, not just some meta-tags on an existing page.

**Comment by isstuev** [comment]
>What suggestion do you have here that could help us rank?
I checked Google Search console and found out that URL https://eth.blockscout.com/gas-tracker wasn't indexed at all. I requested indexing, but it looks like the first problem we have to sold here is how to make google index that page

**Comment by isstuev** [comment]
we can start with fixing sitemap (it doesn't work for the mainnet rn) and I also proposed a fix for our navigation markup
