### ISSUE TITLE
Celo: Cross-link to epoch block on the regular block view

### ISSUE THREAD

**Issue by fedor-ivn** [blockscout/frontend#2365]
Add a cross-link to the epoch block on the [regular block view](https://celo-alfajores.blockscout.com/block/28044523).

**Formula for calculating epoch block number:**

```
epoch_block_number = block.celo.epoch_number * 17280
```

**:warning: Important Detail:** the epoch mechanics changed when Celo transitioned to L2, so this feature should only be enabled for historical blocks. It would be ideal to configure this using an environment variable, like `CELO_L2_UPGRADE_FROM_BLOCK`. For the Alfajores testnet, the last block before the L2 transition is [26369280](https://celo-alfajores.blockscout.com/block/0x9dece1eb0e26a95fdf57d2f3a65a6f2e00ca0192e8e3dd157eca0cd323670fa2?tab=epoch_rewards) (Epoch 1526).

![Image](https://github.com/user-attachments/assets/5f88887c-700e-4af7-80f9-5bc19e3fac22)

**Comment by tom2drum** [comment]
New frontend ENVs example (for Alfajores testnet):
```
NEXT_PUBLIC_CELO_ENABLED=true
NEXT_PUBLIC_CELO_L2_UPGRADE_BLOCK=26369280
```
