### ISSUE TITLE
Zilliqa: Scilla transactions and logs

### ISSUE THREAD

**Issue by fedor-ivn** [blockscout/frontend#2398]
In Zilliqa, certain transactions are designated as Scilla transactions. At the APIv2 level, they are identified by the `zilliqa.is_scilla` field. When this field is set to `true`, the transaction is recognized as a Scilla transaction.

The only customization required for Scilla transactions at this stage is to decode the Raw input as **UTF-8** by default, instead of hex. This decoding should also be applied to the log data by default (excluding topics).

![Image](https://github.com/user-attachments/assets/d8d4010b-6724-4682-9bd0-8e785577a2f8)

**Comment by fedor-ivn** [comment]
Example of Scilla transaction: [UI](https://zilliqa-prototestnet.blockscout.com/tx/0xa852ef27eaa473bc9dcabd95b5cf2d7baf81afbf99e12fae205be1893fa34844) and [APIv2](https://zilliqa-prototestnet.blockscout.com/api/v2/transactions/0xa852ef27eaa473bc9dcabd95b5cf2d7baf81afbf99e12fae205be1893fa34844)

**Comment by tom2drum** [comment]
To implement the necessary changes in the Logs tab on the Address page, we need to make additional modifications on the API side. We should consider adding the `zilliqa.is_scilla` flag to the Address info endpoint response or storing it within the Log model.
