### ISSUE TITLE
no matching manifest for linux/amd64 in the manifest list entries with Docker compose

### ISSUE THREAD

**Issue by ThaiKhim** [blockscout/frontend#2416]
### Description

I built an Explorer panel using Docker however an error occurred:`no matching manifest for linux/amd64 in the manifest list entries`

A few days ago I tried a similar deployment and everything was fine until about 8 hours ago, all configurations in the .env files and the server's configuration kept from the first run.
![Screenshot from 2024-11-20 09-19-41](https://github.com/user-attachments/assets/881d1882-d4c7-4b1e-affa-699774035a6e)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Steps to reproduce

- Clone Src from Repo
- Set up .env
- run compose: `sudo docker compose up -d`

### Backend version

v6.9.1

### Elixir & Erlang/OTP versions

Elixir 1.17.3 (compiled with Erlang/OTP 27)

### Operating system

Linux

**Comment by sl1depengwyn** [comment]
Should be fixed now https://github.com/blockscout/frontend/pkgs/container/frontend/308867802?tag=v1.36.2
