### ISSUE TITLE
Virtual memory pointing value of namespace rather than pod

### ISSUE THREAD

**Issue by human-77** [blockscout/frontend#2421]
### Description

I was creating some dashboards to monitor an instance of frontend running on a pod when I found this bizarre value for the virtual memory

 ```
# HELP frontend_process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE frontend_process_virtual_memory_bytes gauge
frontend_process_virtual_memory_bytes 33012293632
```
Using `kubectl describe ns my-namespace` I got:

```
limits.memory                     9829Mi  30Gi
requests.cpu                      1800m   10
requests.ephemeral-storage        0       10Gi
requests.memory                   2560Mi  30Gi
requests.storage                  0       30Gi
```

In other words, despite running on a pod, the virtual memory is pointing the virtual memory of the WHOLE NAMESPACE

### Link to the page

private site

### Steps to reproduce

We are running it on a cloud using helm charts. I believe that you can simply run the pod on a namespace meant for multiple pods and the error should happen.

### App version

v1.36.0

### Browser

Doesn't matter in this case.

### Operating system

Ubuntu docker image

**Comment by tom2drum** [comment]
Hi @human-77. We use the standard `prom-client` library to obtain this metric. I believe a bug lies on their side, specifically in the area where [the metrics are collected](https://github.com/siimon/prom-client/blob/master/lib/metrics/osMemoryHeapLinux.js). In our app, we simply [call](https://github.com/blockscout/frontend/blob/e8a4642497e4d214507035e2c69a398e29923e11/pages/api/metrics.ts#L6C25-L6C46) the `collectDefaultMetrics` method from the library.

**Comment by human-77** [comment]
So what should I do?

Do I open a issue there or there is already something about the issue?

**Comment by tom2drum** [comment]
Yes, I suggest to open a discussion/issue in the `prom-client` repo.

**Comment by human-77** [comment]
Thank for the help!

**Comment by human-77** [comment]
For anyone with the same problem, I opened a new issue [HERE](https://github.com/siimon/prom-client/issues/648).
