### ISSUE TITLE
Contract response not rendered on one of the chains

### ISSUE THREAD

**Issue by klemenfn** [blockscout/frontend#2448]
### Description

Response from a contract call does not render properly on one chain but does on another.

### Link to the page

https://songbird-explorer.flare.network/address/0x11e8d7dcb7e7b62E6984E7fF29C736A8fA857c11?tab=read_contract

### Steps to reproduce

1. Go to https://flare-explorer.flare.network/address/0xe3b151a43b86c6b146a7dB0CdE22AbD8Beb01E2b?tab=read_contract
2. Call method getSharingPercentages
3. Response is rendered
4. Go to https://songbird-explorer.flare.network/address/0x11e8d7dcb7e7b62E6984E7fF29C736A8fA857c11?tab=read_contract
5. Call method getSharingPercentages
6. Response render is empty, network response data seems fine.

### App version

v1.35.2

### Operating system

Linux

**Comment by tom2drum** [comment]
Hey @klemenfn 
I was not able reproduce this issue with the latest Frontend version (`v1.36.4`). I believe it was already fixed.
![Image](https://github.com/user-attachments/assets/0f68bc1d-8cce-40f7-813b-e14a1712939a)
