### ISSUE TITLE
Celo: Do not display `Burnt fees` for the Celo chain type

### ISSUE THREAD

**Issue by fedor-ivn** [blockscout/frontend#2457]
We should not display `Burnt fees` on the block page for celo chain type, as this field conflicts with `Base fee breakdown`.

[Example](https://celo-alfajores.blockscout.com/block/32861685) 

![Image](https://github.com/user-attachments/assets/feb777cb-9a73-4362-95d1-a74e4d3154cd)

**Comment by tom2drum** [comment]
No changes needed in the code right now. The fields could be hidden with `NEXT_PUBLIC_VIEWS_BLOCK_HIDDEN_FIELDS=['burnt_fees']` variable.
