### ISSUE TITLE
marketplace: change the placement of submit button on the marketplace page

### ISSUE THREAD

**Issue by mikhin** [blockscout/frontend#280]
Figma – https://www.figma.com/file/6R0Rfb4nFodpxaq4krHrWT/Blockscout-Apps?node-id=55%3A6768

<img width="341" alt="Screenshot 2022-10-12 at 14 49 18" src="https://user-images.githubusercontent.com/38258318/197979715-cb25852d-0b77-44d2-956a-bc729193edd9.png">

**Comment by maikReal** [comment]
Duplicated. New task: https://github.com/blockscout/frontend/issues/1430

**Comment by maikReal** [comment]
Duplicated. New task: https://github.com/blockscout/frontend/issues/1430
