### ISSUE TITLE
Add private tag option disappears

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/frontend#898]
### Link to the page

https://eth-goerli.blockscout.com/address/0xc0d74A6E896fB8E258D2542C2629f3E06deC824B

### Steps to reproduce

1. Open https://eth-goerli.blockscout.com/address/0xc0d74A6E896fB8E258D2542C2629f3E06deC824B
2. Select More -> "Add private tag"
3. Refresh the page
3. Select it again

Actual result: Option is showing but then disappear
Expected result: Either there should be no option in selection or it should work second time

<img width="884" alt="image" src="https://github.com/blockscout/frontend/assets/108135703/da1b0fc3-cbc1-4ce2-8ed6-499033796951">

### App version

eeeae759

### Browser

113.0.5672.92 x86_64

### Operating system

macOS

**Comment by NikitaSavik** [comment]
Closing due to relevancy. Similar functionality will be developed due to watchlist rework
