### ISSUE TITLE
Add ability to set favicon through environment variable

### ISSUE THREAD

**Issue by tom2drum** [blockscout/frontend#972]
Add possibility to customize app favicon via env variables for the Blockscout explorers running on custom domains.

**Comment by NikitaSavik** [comment]
Decision: going with SVG as general approach and PNG(180x180) for Safari support

**Comment by tom2drum** [comment]
UPD: decided to generate assets bundle with all variations at container start time. By default, using the network icon from variable `NEXT_PUBLIC_NETWORK_ICON`, but the custom file can be provided as well - `NEXT_PUBLIC_FAVICON_MASTER_URL`

**Comment by tom2drum** [comment]
demo - https://review-tom2drum-issue-972.k8s-dev.blockscout.com/
